/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202601GetDecisionEligibilityResponseDataDecisions } from './GetDecisionEligibilityResponseDataDecisions';

export class ReturnRefund202601GetDecisionEligibilityResponseData {
    /**
    * Decision list
    */
    'decisions'?: Array<ReturnRefund202601GetDecisionEligibilityResponseDataDecisions>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "decisions",
            "baseName": "decisions",
            "type": "Array<ReturnRefund202601GetDecisionEligibilityResponseDataDecisions>"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202601GetDecisionEligibilityResponseData.attributeTypeMap;
    }
}

