/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateCreator202409CreatorSearchSampleApplicationFulfillmentsResponseDataFulfillments } from './CreatorSearchSampleApplicationFulfillmentsResponseDataFulfillments';

export class AffiliateCreator202409CreatorSearchSampleApplicationFulfillmentsResponseData {
    /**
    * Creator fulfillment contents.
    */
    'fulfillments'?: Array<AffiliateCreator202409CreatorSearchSampleApplicationFulfillmentsResponseDataFulfillments>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fulfillments",
            "baseName": "fulfillments",
            "type": "Array<AffiliateCreator202409CreatorSearchSampleApplicationFulfillmentsResponseDataFulfillments>"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202409CreatorSearchSampleApplicationFulfillmentsResponseData.attributeTypeMap;
    }
}

