/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202409GetOpenCollaborationSettingsResponseDataOpenCollaborationSettingsAutoAddProduct {
    /**
    * The default commission rate of open collaboration created for the auto-added products.  The unit is 0.01%. For example, to set the default commission rate to 10%, set the value to `1000`. If so, if the price of a product is $50 USD, the creator would receive $5 USD for every piece of product sold.  The range is `[100, 8000]`. When enable=false, this field will not be returned.
    */
    'commissionRate'?: number;
    /**
    * - true: The seller can add existing non-affiliate products to open collaboration at one time, and future products will also be added automatically. - false: Future products will not be added to open collaboration automatically, but existing products\' open collaboration will not be reverted.
    */
    'enable'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "commissionRate",
            "baseName": "commission_rate",
            "type": "number"
        },
        {
            "name": "enable",
            "baseName": "enable",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202409GetOpenCollaborationSettingsResponseDataOpenCollaborationSettingsAutoAddProduct.attributeTypeMap;
    }
}

