/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202409SellerSearchSampleApplicationsFulfillmentsResponseDataFulfillmentsContent } from './SellerSearchSampleApplicationsFulfillmentsResponseDataFulfillmentsContent';
import { AffiliateSeller202409SellerSearchSampleApplicationsFulfillmentsResponseDataFulfillmentsProduct } from './SellerSearchSampleApplicationsFulfillmentsResponseDataFulfillmentsProduct';

export class AffiliateSeller202409SellerSearchSampleApplicationsFulfillmentsResponseDataFulfillments {
    'content'?: AffiliateSeller202409SellerSearchSampleApplicationsFulfillmentsResponseDataFulfillmentsContent;
    'product'?: AffiliateSeller202409SellerSearchSampleApplicationsFulfillmentsResponseDataFulfillmentsProduct;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "AffiliateSeller202409SellerSearchSampleApplicationsFulfillmentsResponseDataFulfillmentsContent"
        },
        {
            "name": "product",
            "baseName": "product",
            "type": "AffiliateSeller202409SellerSearchSampleApplicationsFulfillmentsResponseDataFulfillmentsProduct"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202409SellerSearchSampleApplicationsFulfillmentsResponseDataFulfillments.attributeTypeMap;
    }
}

