/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202409SellerSearchSampleApplicationsFulfillmentsResponseDataFulfillmentsContent {
    /**
    * The cumulative total number of content commented.
    */
    'commentCount'?: number;
    /**
    * - When `format==VIDEO`, it refers to the time when the video is first set to public and linked to the product. - When `format==LIVE`, it refers to the time when the product link is first added to the live stream.
    */
    'createTime'?: number;
    /**
    * The title of video or the description of the live room.
    */
    'description'?: string;
    /**
    * The format of the generated content: - LIVE - `VIDEO`
    */
    'format'?: string;
    /**
    * The video or live room identifier.
    */
    'id'?: string;
    /**
    * The cumulative total number of content liked.
    */
    'likeCount'?: number;
    /**
    * Only when `format==LIVE`. It refers to the time when the product link is removed from the live room. If the product link remains active and is not removed, then it is the end of the live stream.
    */
    'liveEndTime'?: number;
    /**
    * Content page url of TikTok.
    */
    'pageLink'?: string;
    /**
    * The cumulative total number of orders paid for content.
    */
    'paidOrderCount'?: number;
    /**
    * The content source link.
    */
    'url'?: string;
    /**
    * The cumulative total number of content viewed.
    */
    'viewCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "commentCount",
            "baseName": "comment_count",
            "type": "number"
        },
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "number"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "likeCount",
            "baseName": "like_count",
            "type": "number"
        },
        {
            "name": "liveEndTime",
            "baseName": "live_end_time",
            "type": "number"
        },
        {
            "name": "pageLink",
            "baseName": "page_link",
            "type": "string"
        },
        {
            "name": "paidOrderCount",
            "baseName": "paid_order_count",
            "type": "number"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "viewCount",
            "baseName": "view_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202409SellerSearchSampleApplicationsFulfillmentsResponseDataFulfillmentsContent.attributeTypeMap;
    }
}

