/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202409SellerSearchSampleApplicationsFulfillmentsResponseDataFulfillmentsProduct {
    /**
    * The product identifier.
    */
    'id'?: string;
    /**
    * The cover image url of product.
    */
    'mainImageUrl'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "mainImageUrl",
            "baseName": "main_image_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202409SellerSearchSampleApplicationsFulfillmentsResponseDataFulfillmentsProduct.attributeTypeMap;
    }
}

