/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202409UpdateTargetCollaborationResponseDataUpdateFailedSellerContactInfo {
    /**
    * Seller\'s email contact information which has not been successfully updated.
    */
    'email'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202409UpdateTargetCollaborationResponseDataUpdateFailedSellerContactInfo.attributeTypeMap;
    }
}

