/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateCreator202405AddShowcaseProductsRequestBody {
    /**
    * Specifies how products are added to the showcase. This an enumerated type with values: - PRODUCT_ID - PRODUCT_LINK 
    */
    'addType'?: string;
    /**
    * A list of product identifiers included if `add_type` is set to `PRODUCT_ID`. The products associated with the identifiers are added to the showcase. Maximum length of the list is 20 product identifiers.
    */
    'productIds'?: Array<string>;
    /**
    * A list of product URLs included if `add_type` is set to `PRODUCT_LINK`. The products associated with the URLs are added to the showcase. Maximum length of the list is 20 product URLs.
    */
    'productLink'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addType",
            "baseName": "add_type",
            "type": "string"
        },
        {
            "name": "productIds",
            "baseName": "product_ids",
            "type": "Array<string>"
        },
        {
            "name": "productLink",
            "baseName": "product_link",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202405AddShowcaseProductsRequestBody.attributeTypeMap;
    }
}

