/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateCreator202405CreatorSearchOpenCollaborationProductRequestBodySalesPriceRange {
    /**
    * The product price must be greater than this value in order to be included in the search results. The value must be greater than `0`.
    */
    'amountGe'?: string;
    /**
    * The product price must be greater than this value in order to be included in the search results. The value must be greater than `0`. No upper bound is set if this property is not included.
    */
    'amountLt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amountGe",
            "baseName": "amount_ge",
            "type": "string"
        },
        {
            "name": "amountLt",
            "baseName": "amount_lt",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202405CreatorSearchOpenCollaborationProductRequestBodySalesPriceRange.attributeTypeMap;
    }
}

