/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateCreator202405CreatorSearchOpenCollaborationProductRequestBodyCommissionRateRange {
    /**
    * The commission rate must be greater than this value in order to be included in the search results. The commission rate is expressed in hundredths of a percent. For example, `3587` is a commission rate of `35.87%`. This value must a minimum of `1000`. 
    */
    'rateGe'?: number;
    /**
    * The commission rate must be less than this value in order to be included in the search results. The commission rate is expressed in hundredths of a percent. For example, `3587` is a commission rate of `35.87%`. This value must a minimum of `1000`. 
    */
    'rateLt'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "rateGe",
            "baseName": "rate_ge",
            "type": "number"
        },
        {
            "name": "rateLt",
            "baseName": "rate_lt",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202405CreatorSearchOpenCollaborationProductRequestBodyCommissionRateRange.attributeTypeMap;
    }
}

