/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateCreator202405GetShowcaseProductsResponseDataProductsAdditionCustomizedMainImages } from './GetShowcaseProductsResponseDataProductsAdditionCustomizedMainImages';

export class AffiliateCreator202405GetShowcaseProductsResponseDataProductsAddition {
    /**
    * A list of product images.
    */
    'customizedMainImages'?: Array<AffiliateCreator202405GetShowcaseProductsResponseDataProductsAdditionCustomizedMainImages>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "customizedMainImages",
            "baseName": "customized_main_images",
            "type": "Array<AffiliateCreator202405GetShowcaseProductsResponseDataProductsAdditionCustomizedMainImages>"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202405GetShowcaseProductsResponseDataProductsAddition.attributeTypeMap;
    }
}

