/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborations } from './SearchCreatorTargetCollaborationsResponseDataTargetCollaborations';

export class AffiliateCreator202405SearchCreatorTargetCollaborationsResponseData {
    /**
    * An opaque token used to retrieve the next page of a paginated result set.
    */
    'nextPageToken'?: string;
    /**
    * A list of target collaboration objects.
    */
    'targetCollaborations'?: Array<AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborations>;
    /**
    * The total number of target collaboration groups in the response.
    */
    'totalCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "targetCollaborations",
            "baseName": "target_collaborations",
            "type": "Array<AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborations>"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202405SearchCreatorTargetCollaborationsResponseData.attributeTypeMap;
    }
}

