/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProductsCommission } from './SearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProductsCommission';

export class AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProducts {
    'commission'?: AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProductsCommission;
    /**
    * The product identifier.
    */
    'id'?: string;
    /**
    * The product image URL in the TikTok Shop.
    */
    'mainImageUrl'?: string;
    /**
    * The product name.
    */
    'title'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "commission",
            "baseName": "commission",
            "type": "AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProductsCommission"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "mainImageUrl",
            "baseName": "main_image_url",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProducts.attributeTypeMap;
    }
}

