/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateCreator202405SearchCreatorAffiliateOrdersResponseDataOrders } from './SearchCreatorAffiliateOrdersResponseDataOrders';

export class AffiliateCreator202405SearchCreatorAffiliateOrdersResponseData {
    /**
    * Next page token
    */
    'nextPageToken'?: string;
    /**
    * Order information
    */
    'orders'?: Array<AffiliateCreator202405SearchCreatorAffiliateOrdersResponseDataOrders>;
    /**
    * Total count of main orders that meet the query criteria.
    */
    'totalCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "orders",
            "baseName": "orders",
            "type": "Array<AffiliateCreator202405SearchCreatorAffiliateOrdersResponseDataOrders>"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202405SearchCreatorAffiliateOrdersResponseData.attributeTypeMap;
    }
}

