/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProducts } from './SearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProducts';

export class AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborations {
    /**
    * The target collaboration identifier.
    */
    'id'?: string;
    /**
    * The target collaboration name.
    */
    'name'?: string;
    /**
    * A list of products associated with the target collaboration.
    */
    'products'?: Array<AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProducts>;
    /**
    * The target collaboration state. This is an enumerated type with values: - LIVE - EXPIRED - DELETED - ENDED
    */
    'status'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProducts>"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborations.attributeTypeMap;
    }
}

