/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202603CreateCompassOfflineExportTaskRequestBody {
    /**
    * End date in the local timezone of the specified region, formatted as YYYYMMDD.   - id：UTC+7   - my：UTC+8   - sg：UTC+8   - vn：UTC+7   - th：UTC+7   - ph：UTC+8   - sa：UTC+3   - us：UTC-8   - mx：UTC-6   - br：UTC-3   - jp：UTC+9   - gb：UTC+0   - ie：UTC+0   - es：UTC+1   - de：UTC+1   - fr：UTC+1   - it：UTC+1   - pl：UTC+1   - nl：UTC+1   - be：UTC+1   - cz：UTC+1   - at：UTC+1   - gr：UTC+2   - pt：UTC+0   - hu：UTC+1
    */
    'endDay'?: number;
    /**
    * Allowed values: CREATOR, BASE.
    */
    'moduleType'?: string;
    /**
    * Plan type. Allowed values: ALL, TARGET, OPEN, PARTNER.
    */
    'planType'?: string;
    /**
    * Time window type. Allowed values: PAST_24H, PAST_7_DAYS, PAST_30_DAYS.
    */
    'windowType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "endDay",
            "baseName": "end_day",
            "type": "number"
        },
        {
            "name": "moduleType",
            "baseName": "module_type",
            "type": "string"
        },
        {
            "name": "planType",
            "baseName": "plan_type",
            "type": "string"
        },
        {
            "name": "windowType",
            "baseName": "window_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202603CreateCompassOfflineExportTaskRequestBody.attributeTypeMap;
    }
}

