/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202603DownloadCompassTaskFileResponseDataFile } from './DownloadCompassTaskFileResponseDataFile';

export class AffiliateSeller202603DownloadCompassTaskFileResponseData {
    'file'?: AffiliateSeller202603DownloadCompassTaskFileResponseDataFile;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "file",
            "baseName": "file",
            "type": "AffiliateSeller202603DownloadCompassTaskFileResponseDataFile"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202603DownloadCompassTaskFileResponseData.attributeTypeMap;
    }
}

