/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule {
    /**
    * If set to `true`, free samples are provided to creators invited to the target collaboration group. If set to `false`, free samples are not provided.
    */
    'hasFreeSample'?: boolean;
    /**
    * If set to `true`, creators invited to the target collaboration are exempt from seller review and are automatically approved for a free  product sample. Note that the `has_free_sample` property overrides the free sample behavior. 
    */
    'isSampleApprovalExempt'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hasFreeSample",
            "baseName": "has_free_sample",
            "type": "boolean"
        },
        {
            "name": "isSampleApprovalExempt",
            "baseName": "is_sample_approval_exempt",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202405CreateTargetCollaborationRequestBodyFreeSampleRule.attributeTypeMap;
    }
}

