/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202602SearchSessionsResponseDataSessions } from './SearchSessionsResponseDataSessions';

export class CustomerService202602SearchSessionsResponseData {
    /**
    * If there is no more record, this field will be \"\"(empty string).
    */
    'nextPageToken'?: string;
    /**
    * Session info.
    */
    'sessions'?: Array<CustomerService202602SearchSessionsResponseDataSessions>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "sessions",
            "baseName": "sessions",
            "type": "Array<CustomerService202602SearchSessionsResponseDataSessions>"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202602SearchSessionsResponseData.attributeTypeMap;
    }
}

