/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessions } from './GetShopLIVEPerformanceListResponseDataLiveStreamSessions';

export class Analytics202508GetShopLIVEPerformanceListResponseData {
    /**
    * Latest date in local timezone where data is ready (ISO 8601 format).
    */
    'latestAvailableDate'?: string;
    /**
    * List of live performance metrics.
    */
    'liveStreamSessions'?: Array<Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessions>;
    /**
    * Page token for the next page request.
    */
    'nextPageToken'?: string;
    /**
    * Total number of LIVE stream sessions.
    */
    'totalCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "latestAvailableDate",
            "baseName": "latest_available_date",
            "type": "string"
        },
        {
            "name": "liveStreamSessions",
            "baseName": "live_stream_sessions",
            "type": "Array<Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessions>"
        },
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202508GetShopLIVEPerformanceListResponseData.attributeTypeMap;
    }
}

