/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance {
    /**
    * Average concurrent users
    */
    'acu'?: number;
    /**
    * The average time each user spent watching LIVEs. Total viewing time divided by number of views, in seconds.
    */
    'avgViewingDuration'?: string;
    /**
    * The percentage of viewers who clicked on product links after seeing them in this LIVE. Number of clicks divided by the number of views, multiplied by 100.
    */
    'clickThroughRate'?: string;
    /**
    * Number of comments on the LIVE video posted during the selected period.
    */
    'comments'?: number;
    /**
    * The number of likes a LIVE video received during the selected time period.
    */
    'likes'?: number;
    /**
    * The number of viewers who followed creators from the video during the selected period.
    */
    'newFollowers'?: number;
    /**
    * Peak concurrent users
    */
    'pcu'?: number;
    /**
    * Number of product clicks during the LIVE video posted during the selected period, including clicks on product lists and product cards.
    */
    'productClicks'?: number;
    /**
    * Number of product impressions during the LIVE video posted during the selected period, including product lists and product cards
    */
    'productImpressions'?: number;
    /**
    * Number of times the LIVE video posted during the selected period were shared.
    */
    'shares'?: number;
    /**
    * Number of unique viewers of the LIVE video posted during the selected period.
    */
    'viewers'?: number;
    /**
    * Number of views for the LIVE video posted during the selected period.
    */
    'views'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "acu",
            "baseName": "acu",
            "type": "number"
        },
        {
            "name": "avgViewingDuration",
            "baseName": "avg_viewing_duration",
            "type": "string"
        },
        {
            "name": "clickThroughRate",
            "baseName": "click_through_rate",
            "type": "string"
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "number"
        },
        {
            "name": "likes",
            "baseName": "likes",
            "type": "number"
        },
        {
            "name": "newFollowers",
            "baseName": "new_followers",
            "type": "number"
        },
        {
            "name": "pcu",
            "baseName": "pcu",
            "type": "number"
        },
        {
            "name": "productClicks",
            "baseName": "product_clicks",
            "type": "number"
        },
        {
            "name": "productImpressions",
            "baseName": "product_impressions",
            "type": "number"
        },
        {
            "name": "shares",
            "baseName": "shares",
            "type": "number"
        },
        {
            "name": "viewers",
            "baseName": "viewers",
            "type": "number"
        },
        {
            "name": "views",
            "baseName": "views",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance.attributeTypeMap;
    }
}

