/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance } from './GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance';
import { Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsSalesPerformance } from './GetShopLIVEPerformanceListResponseDataLiveStreamSessionsSalesPerformance';

export class Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessions {
    /**
    * End time of the LIVE, unix timestamp GMT (UTC+00:00).
    */
    'endTime'?: string;
    /**
    * ID of the LIVE
    */
    'id'?: string;
    'interactionPerformance'?: Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance;
    'salesPerformance'?: Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsSalesPerformance;
    /**
    * Start time of the LIVE, unix timestamp GMT (UTC+00:00).
    */
    'startTime'?: string;
    /**
    * Title of the LIVE
    */
    'title'?: string;
    /**
    * The host\'s username
    */
    'username'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "interactionPerformance",
            "baseName": "interaction_performance",
            "type": "Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance"
        },
        {
            "name": "salesPerformance",
            "baseName": "sales_performance",
            "type": "Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsSalesPerformance"
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessions.attributeTypeMap;
    }
}

