/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202309CheckProductListingRequestBodyOption {
    /**
    * Asynchronous Verification ID: When \"Asynchronous Acquisition of Product Information Verification Result = Yes\", the asynchronous verification ID needs to be provided, and the verification result of abnormal product information will be obtained based on this ID subsequently
    */
    'gneAsyncCheckSessionId'?: string;
    /**
    * Asynchronous Product Information Verification: If you need to obtain the product information verification result asynchronously, select this field
    */
    'needTriggerGneAsyncCheck'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "gneAsyncCheckSessionId",
            "baseName": "gne_async_check_session_id",
            "type": "string"
        },
        {
            "name": "needTriggerGneAsyncCheck",
            "baseName": "need_trigger_gne_async_check",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Product202309CheckProductListingRequestBodyOption.attributeTypeMap;
    }
}

