/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202604GetOpportunityDetailResponseDataOpportunity } from './GetOpportunityDetailResponseDataOpportunity';

export class Product202604GetOpportunityDetailResponseData {
    'opportunity'?: Product202604GetOpportunityDetailResponseDataOpportunity;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "opportunity",
            "baseName": "opportunity",
            "type": "Product202604GetOpportunityDetailResponseDataOpportunity"
        }    ];

    static getAttributeTypeMap() {
        return Product202604GetOpportunityDetailResponseData.attributeTypeMap;
    }
}

