/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202604GetOpportunityDetailResponseDataOpportunityBasicInfo } from './GetOpportunityDetailResponseDataOpportunityBasicInfo';
import { Product202604GetOpportunityDetailResponseDataOpportunityContentData } from './GetOpportunityDetailResponseDataOpportunityContentData';
import { Product202604GetOpportunityDetailResponseDataOpportunityListingCriteria } from './GetOpportunityDetailResponseDataOpportunityListingCriteria';
import { Product202604GetOpportunityDetailResponseDataOpportunityMarketData } from './GetOpportunityDetailResponseDataOpportunityMarketData';

export class Product202604GetOpportunityDetailResponseDataOpportunity {
    /**
    * Recommended action type: LIST_SAME（发同款）/ LIST_SIMILAR（发相似品）
    */
    'actionType'?: string;
    'basicInfo'?: Product202604GetOpportunityDetailResponseDataOpportunityBasicInfo;
    'contentData'?: Product202604GetOpportunityDetailResponseDataOpportunityContentData;
    /**
    * Unique ID of the opportunity
    */
    'id'?: string;
    'listingCriteria'?: Product202604GetOpportunityDetailResponseDataOpportunityListingCriteria;
    'marketData'?: Product202604GetOpportunityDetailResponseDataOpportunityMarketData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "actionType",
            "baseName": "action_type",
            "type": "string"
        },
        {
            "name": "basicInfo",
            "baseName": "basic_info",
            "type": "Product202604GetOpportunityDetailResponseDataOpportunityBasicInfo"
        },
        {
            "name": "contentData",
            "baseName": "content_data",
            "type": "Product202604GetOpportunityDetailResponseDataOpportunityContentData"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "listingCriteria",
            "baseName": "listing_criteria",
            "type": "Product202604GetOpportunityDetailResponseDataOpportunityListingCriteria"
        },
        {
            "name": "marketData",
            "baseName": "market_data",
            "type": "Product202604GetOpportunityDetailResponseDataOpportunityMarketData"
        }    ];

    static getAttributeTypeMap() {
        return Product202604GetOpportunityDetailResponseDataOpportunity.attributeTypeMap;
    }
}

