/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202604GetSubmissionRecordsResponseDataDataSubmissions } from './GetSubmissionRecordsResponseDataDataSubmissions';

export class Product202604GetSubmissionRecordsResponseDataData {
    /**
    * Token for fetching next page. Empty if no more pages.
    */
    'nextPageToken'?: string;
    /**
    * List of submission records.
    */
    'submissions'?: Array<Product202604GetSubmissionRecordsResponseDataDataSubmissions>;
    /**
    * Total number of matching submissions (approximate).
    */
    'totalCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "submissions",
            "baseName": "submissions",
            "type": "Array<Product202604GetSubmissionRecordsResponseDataDataSubmissions>"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Product202604GetSubmissionRecordsResponseDataData.attributeTypeMap;
    }
}

