/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusActualCofundedCreatorBonusAmount } from './SearchSellerAffiliateOrdersResponseDataOrdersSkusActualCofundedCreatorBonusAmount';
import { AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusActualCommissionBase } from './SearchSellerAffiliateOrdersResponseDataOrdersSkusActualCommissionBase';
import { AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusActualPaidCommission } from './SearchSellerAffiliateOrdersResponseDataOrdersSkusActualPaidCommission';
import { AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusActualPaidPartnerCommission } from './SearchSellerAffiliateOrdersResponseDataOrdersSkusActualPaidPartnerCommission';
import { AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusActualPaidShopAdsCommission } from './SearchSellerAffiliateOrdersResponseDataOrdersSkusActualPaidShopAdsCommission';
import { AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedCofundedCreatorBonusAmount } from './SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedCofundedCreatorBonusAmount';
import { AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedCommissionBase } from './SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedCommissionBase';
import { AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedPaidCommission } from './SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedPaidCommission';
import { AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedPaidPartnerCommission } from './SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedPaidPartnerCommission';
import { AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedPaidShopAdsCommission } from './SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedPaidShopAdsCommission';
import { AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusPrice } from './SearchSellerAffiliateOrdersResponseDataOrdersSkusPrice';

export class AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkus {
    'actualCofundedCreatorBonusAmount'?: AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusActualCofundedCreatorBonusAmount;
    'actualCommissionBase'?: AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusActualCommissionBase;
    'actualPaidCommission'?: AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusActualPaidCommission;
    'actualPaidPartnerCommission'?: AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusActualPaidPartnerCommission;
    'actualPaidShopAdsCommission'?: AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusActualPaidShopAdsCommission;
    /**
    * The ID of the TAP campaign in which the product is enrolled.
    */
    'campaignId'?: string;
    /**
    * Determine order commission be calculated based on fixed commission model or tiering model
    */
    'commissionModel'?: string;
    /**
    * The commission rate established by the seller to be paid to creators involved in the collaboration, expressed in hundredths of a percent. For example, 1550 represents a commission rate of 15.50%. Please note that we only return the value when this order is directly generated from your creator. If you are working with partner, please refer to partner_commission_rate.
    */
    'commissionRate'?: string;
    /**
    * Between Seller & Creator percentagecommission. When tiering commission model applied, will return each tier\'s commission rate seller set.
    */
    'commissionTierSetting'?: string;
    /**
    * The content identifier.
    */
    'contentId'?: string;
    /**
    * The content format of the creator content through which the order was created. Possible values: - SHOP - VIDEO - LIVE - PRE_LIVE - PROMOTION_PAGE - LINKSHARE
    */
    'contentType'?: string;
    /**
    * The username of the creator that\'s participating in the specified open collaboration.
    */
    'creatorUsername'?: string;
    'estimatedCofundedCreatorBonusAmount'?: AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedCofundedCreatorBonusAmount;
    'estimatedCommissionBase'?: AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedCommissionBase;
    'estimatedPaidCommission'?: AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedPaidCommission;
    'estimatedPaidPartnerCommission'?: AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedPaidPartnerCommission;
    'estimatedPaidShopAdsCommission'?: AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedPaidShopAdsCommission;
    /**
    * Return yes when this sku is fully returned/refunded. No commission given when full return/refund
    */
    'fullyReturn'?: string;
    /**
    * The ID of the open collaboration in which the product is enrolled.
    */
    'openCollaborationId'?: string;
    /**
    * The commission rate established by the seller to be paid to affiliate partner involved in the collaboration, expressed in hundredths of a percent. For example, 1550 represents a commission rate of 15.50%.
    */
    'partnerCommissionRate'?: string;
    'price'?: AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusPrice;
    /**
    * The product  ID in TikTok Shop.
    */
    'productId'?: string;
    /**
    * The SKU quantity for the order.
    */
    'quantity'?: number;
    /**
    * Field depreciated, no value return.please refer to fully_return.
    */
    'refundedQuantity'?: number;
    /**
    * Field depreciated, no value return.please refer to fully_return.
    */
    'returnedQuantity'?: number;
    /**
    * The current settlement status of the sku order. Possible options are: - Unknown: The status of the order is undefined. It might be updated later. - AWAITING PAYMENT：The order hasn\'t been paid by customer yet, only estimated commission is available - To-SETTLE：The order is waiting for settlement, only estimated commission is available - SETTLED: The commission of the order is already settled. - INELIGIBLE: The order has been returned/refunded/canceled by the buyer, and no commission will be settled.
    */
    'settlementStatus'?: string;
    /**
    * The commission rate for orders generated through Shop Ads.
    */
    'shopAdsCommissionRate'?: string;
    /**
    * The ID of your SKU
    */
    'skuId'?: string;
    /**
    * The ID of the target collaboration in which the product is enrolled.
    */
    'targetCollaborationId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "actualCofundedCreatorBonusAmount",
            "baseName": "actual_cofunded_creator_bonus_amount",
            "type": "AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusActualCofundedCreatorBonusAmount"
        },
        {
            "name": "actualCommissionBase",
            "baseName": "actual_commission_base",
            "type": "AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusActualCommissionBase"
        },
        {
            "name": "actualPaidCommission",
            "baseName": "actual_paid_commission",
            "type": "AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusActualPaidCommission"
        },
        {
            "name": "actualPaidPartnerCommission",
            "baseName": "actual_paid_partner_commission",
            "type": "AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusActualPaidPartnerCommission"
        },
        {
            "name": "actualPaidShopAdsCommission",
            "baseName": "actual_paid_shop_ads_commission",
            "type": "AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusActualPaidShopAdsCommission"
        },
        {
            "name": "campaignId",
            "baseName": "campaign_id",
            "type": "string"
        },
        {
            "name": "commissionModel",
            "baseName": "commission_model",
            "type": "string"
        },
        {
            "name": "commissionRate",
            "baseName": "commission_rate",
            "type": "string"
        },
        {
            "name": "commissionTierSetting",
            "baseName": "commission_tier_setting",
            "type": "string"
        },
        {
            "name": "contentId",
            "baseName": "content_id",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "string"
        },
        {
            "name": "creatorUsername",
            "baseName": "creator_username",
            "type": "string"
        },
        {
            "name": "estimatedCofundedCreatorBonusAmount",
            "baseName": "estimated_cofunded_creator_bonus_amount",
            "type": "AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedCofundedCreatorBonusAmount"
        },
        {
            "name": "estimatedCommissionBase",
            "baseName": "estimated_commission_base",
            "type": "AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedCommissionBase"
        },
        {
            "name": "estimatedPaidCommission",
            "baseName": "estimated_paid_commission",
            "type": "AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedPaidCommission"
        },
        {
            "name": "estimatedPaidPartnerCommission",
            "baseName": "estimated_paid_partner_commission",
            "type": "AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedPaidPartnerCommission"
        },
        {
            "name": "estimatedPaidShopAdsCommission",
            "baseName": "estimated_paid_shop_ads_commission",
            "type": "AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusEstimatedPaidShopAdsCommission"
        },
        {
            "name": "fullyReturn",
            "baseName": "fully_return",
            "type": "string"
        },
        {
            "name": "openCollaborationId",
            "baseName": "open_collaboration_id",
            "type": "string"
        },
        {
            "name": "partnerCommissionRate",
            "baseName": "partner_commission_rate",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkusPrice"
        },
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "refundedQuantity",
            "baseName": "refunded_quantity",
            "type": "number"
        },
        {
            "name": "returnedQuantity",
            "baseName": "returned_quantity",
            "type": "number"
        },
        {
            "name": "settlementStatus",
            "baseName": "settlement_status",
            "type": "string"
        },
        {
            "name": "shopAdsCommissionRate",
            "baseName": "shop_ads_commission_rate",
            "type": "string"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        },
        {
            "name": "targetCollaborationId",
            "baseName": "target_collaboration_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkus.attributeTypeMap;
    }
}

