/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkus } from './SearchSellerAffiliateOrdersResponseDataOrdersSkus';

export class AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrders {
    /**
    * The date and time when the order was created. Unix timestamp.
    */
    'createTime'?: number;
    /**
    * The date and time when the order was delivered. Unix timestamp.
    */
    'deliveryTime'?: number;
    /**
    * The order ID.
    */
    'id'?: string;
    /**
    * The list of SKUs that are included in this order.
    */
    'skus'?: Array<AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkus>;
    /**
    * Field depreciated, we won\'t return the value. For your skus settlement status, please find below settle_status.
    */
    'status'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "number"
        },
        {
            "name": "deliveryTime",
            "baseName": "delivery_time",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "skus",
            "baseName": "skus",
            "type": "Array<AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrdersSkus>"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202410SearchSellerAffiliateOrdersResponseDataOrders.attributeTypeMap;
    }
}

