/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateCreator202412GetCreatorSampleApplicationDetailResponseDataSampleApplicationSampleProduct {
    /**
    * The product identifier.
    */
    'id'?: string;
    /**
    * The SKU identifier.
    */
    'skuId'?: string;
    /**
    * Sku property name list for this sku id.
    */
    'skuSalePropertyValueNames'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        },
        {
            "name": "skuSalePropertyValueNames",
            "baseName": "sku_sale_property_value_names",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202412GetCreatorSampleApplicationDetailResponseDataSampleApplicationSampleProduct.attributeTypeMap;
    }
}

