/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusTrace {
    /**
    * When `trace.type==GENERAL`, the value is {eid} you provided in `sharing_link`; when `trace.type==SPECIFIC`, the value is the same as `publisher_id`.
    */
    'id'?: string;
    /**
    * For the orders coming from the sharing links for specific publishers, the value is `SPECIFIC`; for the orders coming from the general sharing links, the value is `GENERAL`.
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusTrace.attributeTypeMap;
    }
}

