/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateCreator202505CreatorSearchAffiliateTraceOrdersRequestBody {
    /**
    * Filter orders to include only those with the specified `time_type` timestamp greater than or equal to time_ge and less than time_lt. Unix timestamp. Note: `time_ge` and `time_lt` together constitute the creation time filter condition.
    */
    'timeGe'?: number;
    /**
    * Filter orders to include only those with the specified `time_type` timestamp greater than or equal to time_ge and less than time_lt.Unix timestamp.
    */
    'timeLt'?: number;
    /**
    * Specifies the type of timestamp to filter the orders by. The query time range (time_ge and time_lt) will be applied to the selected time type. Possible values: - PAY_TIME: Filter based on the order payment time. - DELIVERY_TIME: Filter based on the order delivery/shipment time. - SETTLE_TIME: Filter based on the order settlement time. - CREATE_TIME (default): Filter based on the order creation time.
    */
    'timeType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "timeGe",
            "baseName": "time_ge",
            "type": "number"
        },
        {
            "name": "timeLt",
            "baseName": "time_lt",
            "type": "number"
        },
        {
            "name": "timeType",
            "baseName": "time_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202505CreatorSearchAffiliateTraceOrdersRequestBody.attributeTypeMap;
    }
}

