/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrders } from './CreatorSearchAffiliateTraceOrdersResponseDataOrders';

export class AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseData {
    /**
    * An opaque token used to retrieve the next page of a paginated result set. 
    */
    'nextPageToken'?: string;
    /**
    * The order resource.
    */
    'orders'?: Array<AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrders>;
    /**
    * Total count of orders in the response. 
    */
    'totalCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "orders",
            "baseName": "orders",
            "type": "Array<AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseDataOrders>"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202505CreatorSearchAffiliateTraceOrdersResponseData.attributeTypeMap;
    }
}

