/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateCreator202505PostShoppableVideoRequestBodyProductLinkInfo } from './PostShoppableVideoRequestBodyProductLinkInfo';
import { AffiliateCreator202505PostShoppableVideoRequestBodyVideoInfo } from './PostShoppableVideoRequestBodyVideoInfo';

export class AffiliateCreator202505PostShoppableVideoRequestBody {
    'productLinkInfo'?: AffiliateCreator202505PostShoppableVideoRequestBodyProductLinkInfo;
    'videoInfo'?: AffiliateCreator202505PostShoppableVideoRequestBodyVideoInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "productLinkInfo",
            "baseName": "product_link_info",
            "type": "AffiliateCreator202505PostShoppableVideoRequestBodyProductLinkInfo"
        },
        {
            "name": "videoInfo",
            "baseName": "video_info",
            "type": "AffiliateCreator202505PostShoppableVideoRequestBodyVideoInfo"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202505PostShoppableVideoRequestBody.attributeTypeMap;
    }
}

