/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateCreator202505PostShoppableVideoRequestBodyVideoInfo {
    /**
    * Video file_id from [Upload Shoppable Video File]
    */
    'fileId'?: string;
    /**
    * The video caption.  The maximum length is 2200 in UTF-16 runes. If not specified, the ticket post will not have any captions.
    */
    'title'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fileId",
            "baseName": "file_id",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202505PostShoppableVideoRequestBodyVideoInfo.attributeTypeMap;
    }
}

