/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateCreator202505UploadShoppableVideoFileResponseDataVideoFile {
    /**
    * The id from of the uploaded video file.
    */
    'id'?: string;
    /**
    * Upload file md5 checksum
    */
    'md5'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "md5",
            "baseName": "md5",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202505UploadShoppableVideoFileResponseDataVideoFile.attributeTypeMap;
    }
}

