/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Fulfillment202601RedeemInfoCallbackResponseDataOrderStatuses } from './RedeemInfoCallbackResponseDataOrderStatuses';

export class Fulfillment202601RedeemInfoCallbackResponseData {
    /**
    * Callback result.For partial failure usage, if some of order line id in the request fail, it will be recorded with a none zero status_code.
    */
    'orderStatuses'?: Array<Fulfillment202601RedeemInfoCallbackResponseDataOrderStatuses>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderStatuses",
            "baseName": "order_statuses",
            "type": "Array<Fulfillment202601RedeemInfoCallbackResponseDataOrderStatuses>"
        }    ];

    static getAttributeTypeMap() {
        return Fulfillment202601RedeemInfoCallbackResponseData.attributeTypeMap;
    }
}

