/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Fulfillment202601RedeemInfoCallbackResponseDataOrderStatuses {
    /**
    * Line order id, same as the input line order id.
    */
    'orderLineId'?: string;
    /**
    * Callback status of this line order id. A none zero code represent a failure callback.
    */
    'statusCode'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderLineId",
            "baseName": "order_line_id",
            "type": "string"
        },
        {
            "name": "statusCode",
            "baseName": "status_code",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Fulfillment202601RedeemInfoCallbackResponseDataOrderStatuses.attributeTypeMap;
    }
}

