/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateCreator202511PostShoppablePhotosResponseDataPhoto } from './PostShoppablePhotosResponseDataPhoto';

export class AffiliateCreator202511PostShoppablePhotosResponseData {
    'photo'?: AffiliateCreator202511PostShoppablePhotosResponseDataPhoto;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "photo",
            "baseName": "photo",
            "type": "AffiliateCreator202511PostShoppablePhotosResponseDataPhoto"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202511PostShoppablePhotosResponseData.attributeTypeMap;
    }
}

