/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateCreator202511PostShoppablePhotosRequestBodyLinkInfoLinks {
    /**
    * Photo Anchor Title:The title to be shown on the product anchor. Anchor title should be shorter than 30 characters
    */
    'linkTitle'?: string;
    /**
    * Product ID
    */
    'productId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "linkTitle",
            "baseName": "link_title",
            "type": "string"
        },
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202511PostShoppablePhotosRequestBodyLinkInfoLinks.attributeTypeMap;
    }
}

