/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateCreator202511UploadShoppablePhotoFileResponseDataPhotoFile } from './UploadShoppablePhotoFileResponseDataPhotoFile';

export class AffiliateCreator202511UploadShoppablePhotoFileResponseData {
    'photoFile'?: AffiliateCreator202511UploadShoppablePhotoFileResponseDataPhotoFile;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "photoFile",
            "baseName": "photo_file",
            "type": "AffiliateCreator202511UploadShoppablePhotoFileResponseDataPhotoFile"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202511UploadShoppablePhotoFileResponseData.attributeTypeMap;
    }
}

