/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReviewRating202602ProductReviewRemovalResponseDataDetail } from './ProductReviewRemovalResponseDataDetail';
import { ReviewRating202602ProductReviewRemovalResponseDataErrors } from './ProductReviewRemovalResponseDataErrors';

export class ReviewRating202602ProductReviewRemovalResponseData {
    'detail'?: ReviewRating202602ProductReviewRemovalResponseDataDetail;
    /**
    * The list of errors that occurred.
    */
    'errors'?: Array<ReviewRating202602ProductReviewRemovalResponseDataErrors>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "detail",
            "baseName": "detail",
            "type": "ReviewRating202602ProductReviewRemovalResponseDataDetail"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<ReviewRating202602ProductReviewRemovalResponseDataErrors>"
        }    ];

    static getAttributeTypeMap() {
        return ReviewRating202602ProductReviewRemovalResponseData.attributeTypeMap;
    }
}

