/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202412GetConversationListResponseDataConversations } from './GetConversationListResponseDataConversations';

export class AffiliateSeller202412GetConversationListResponseData {
    /**
    * The conversation list.
    */
    'conversations'?: Array<AffiliateSeller202412GetConversationListResponseDataConversations>;
    /**
    * Whether there are more conversations.
    */
    'hasMore'?: boolean;
    /**
    * Cursor for the next page request.
    */
    'nextPageToken'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "conversations",
            "baseName": "conversations",
            "type": "Array<AffiliateSeller202412GetConversationListResponseDataConversations>"
        },
        {
            "name": "hasMore",
            "baseName": "has_more",
            "type": "boolean"
        },
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202412GetConversationListResponseData.attributeTypeMap;
    }
}

