/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202412GetMessageintheConversationResponseDataMessagesMessageBody } from './GetMessageintheConversationResponseDataMessagesMessageBody';

export class AffiliateSeller202412GetMessageintheConversationResponseDataMessages {
    /**
    * Index of the message in the conversation. Higher index corresponds to newer message.
    */
    'conversationIndex'?: string;
    'messageBody'?: AffiliateSeller202412GetMessageintheConversationResponseDataMessagesMessageBody;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "conversationIndex",
            "baseName": "conversation_index",
            "type": "string"
        },
        {
            "name": "messageBody",
            "baseName": "message_body",
            "type": "AffiliateSeller202412GetMessageintheConversationResponseDataMessagesMessageBody"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202412GetMessageintheConversationResponseDataMessages.attributeTypeMap;
    }
}

