/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202412GetOpenCollaborationCreatorContentDetailResponseDataCreatorContentDetails } from './GetOpenCollaborationCreatorContentDetailResponseDataCreatorContentDetails';
import { AffiliateSeller202412GetOpenCollaborationCreatorContentDetailResponseDataProduct } from './GetOpenCollaborationCreatorContentDetailResponseDataProduct';

export class AffiliateSeller202412GetOpenCollaborationCreatorContentDetailResponseData {
    /**
    * Creators\' posting content details.
    */
    'creatorContentDetails'?: Array<AffiliateSeller202412GetOpenCollaborationCreatorContentDetailResponseDataCreatorContentDetails>;
    /**
    * Next page token
    */
    'nextPageToken'?: string;
    'product'?: AffiliateSeller202412GetOpenCollaborationCreatorContentDetailResponseDataProduct;
    /**
    * Total count of creators that satisfy all the input search conditions.
    */
    'totalCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "creatorContentDetails",
            "baseName": "creator_content_details",
            "type": "Array<AffiliateSeller202412GetOpenCollaborationCreatorContentDetailResponseDataCreatorContentDetails>"
        },
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "product",
            "baseName": "product",
            "type": "AffiliateSeller202412GetOpenCollaborationCreatorContentDetailResponseDataProduct"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202412GetOpenCollaborationCreatorContentDetailResponseData.attributeTypeMap;
    }
}

