/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaboration } from './QueryTargetCollaborationDetailResponseDataTargetCollaboration';

export class AffiliateSeller202412QueryTargetCollaborationDetailResponseData {
    'targetCollaboration'?: AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaboration;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "targetCollaboration",
            "baseName": "target_collaboration",
            "type": "AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaboration"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202412QueryTargetCollaborationDetailResponseData.attributeTypeMap;
    }
}

