/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar } from './QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar';

export class AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationCreators {
    'avatar'?: AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar;
    /**
    * The status of the creator in the current target cooperation. Field values: - NORMAL: The status of the creator in the current target collaboration is normal. - DELETING: The status of the creator in the current target collaboration is deleting.The creator\'s product promotion relationship in the DELETING status will end the delayed effectiveness status and flow to the DELETED status at 00:00 the next day. - DELETED: The status of the creator in the current target collaboration is deleted.
    */
    'collaborationStatus'?: string;
    /**
    * This field indicates the number of products creator has posted video or live from target collaboration. The count includes NORMAL and DELETING states.
    */
    'contentProductCount'?: number;
    /**
    * The TikTok nick name.
    */
    'nickname'?: string;
    /**
    * The effectiveness of the creators\' commissions and products. Field values: - EFFECTIVE_ALL: The current product commission is effective for all creators. - EFFECTIVE_PARTIALLY: The current product commission are effective for some creators. - EFFECTIVE_NONE: The current product commission is not effective for all creators. Normally, the commission rate for all products under Target Collaboration is effective. If the merchant participates in TOP_CREATOR_PROGRAM, and TOP_CREATOR_PROGRAM includes the current creator and some products, the commission rate will be based on TOP_CREATOR_PROGRAM. The products\' commission under the current Target Collaboration will only be partially effective for the creator, corresponding to EFFECTIVE_PARTIALLY status.
    */
    'productEffectiveStatus'?: string;
    /**
    * The regions in which the creator is eligible to promote products in showcases, videos, and live streams.
    */
    'selectionRegion'?: string;
    /**
    * This field indicates the number of products creator has added  to the showcase from target collaboration. The count includes NORMAL and DELETING states.
    */
    'showcaseProductCount'?: number;
    /**
    * The TikTok user name.
    */
    'username'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationCreatorsAvatar"
        },
        {
            "name": "collaborationStatus",
            "baseName": "collaboration_status",
            "type": "string"
        },
        {
            "name": "contentProductCount",
            "baseName": "content_product_count",
            "type": "number"
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string"
        },
        {
            "name": "productEffectiveStatus",
            "baseName": "product_effective_status",
            "type": "string"
        },
        {
            "name": "selectionRegion",
            "baseName": "selection_region",
            "type": "string"
        },
        {
            "name": "showcaseProductCount",
            "baseName": "showcase_product_count",
            "type": "number"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202412QueryTargetCollaborationDetailResponseDataTargetCollaborationCreators.attributeTypeMap;
    }
}

