/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202412SearchOpenCollaborationResponseDataOpenCollaborations } from './SearchOpenCollaborationResponseDataOpenCollaborations';

export class AffiliateSeller202412SearchOpenCollaborationResponseData {
    /**
    * Next page token
    */
    'nextPageToken'?: string;
    /**
    * The open collaborations
    */
    'openCollaborations'?: Array<AffiliateSeller202412SearchOpenCollaborationResponseDataOpenCollaborations>;
    /**
    * Total count of products that satisfy all the input search conditions.
    */
    'totalCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "openCollaborations",
            "baseName": "open_collaborations",
            "type": "Array<AffiliateSeller202412SearchOpenCollaborationResponseDataOpenCollaborations>"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202412SearchOpenCollaborationResponseData.attributeTypeMap;
    }
}

