/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202412SearchOpenCollaborationResponseDataOpenCollaborationsCurrentCommission {
    /**
    * The effective end time of the commission rate.
    */
    'endTime'?: number;
    /**
    * The commission rate for this product is set by merchants for creators\' public promotion. The range of this value is [100, 8000]. This value is expressed in 1/10000 increments. For example: 3000 means the actual commission rate is 30.00%, and 3555 means 35.55%
    */
    'rate'?: number;
    /**
    * The time when the commission rate becomes effective.
    */
    'startTime'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "number"
        },
        {
            "name": "rate",
            "baseName": "rate",
            "type": "number"
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202412SearchOpenCollaborationResponseDataOpenCollaborationsCurrentCommission.attributeTypeMap;
    }
}

