/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Fbt202602GetInboundOrderResponseDataInboundOrdersCartonDetails } from './GetInboundOrderResponseDataInboundOrdersCartonDetails';
import { Fbt202602GetInboundOrderResponseDataInboundOrdersInboundGoodsLotReceiveItemDetails } from './GetInboundOrderResponseDataInboundOrdersInboundGoodsLotReceiveItemDetails';
import { Fbt202602GetInboundOrderResponseDataInboundOrdersLogisticInfoList } from './GetInboundOrderResponseDataInboundOrdersLogisticInfoList';
import { Fbt202602GetInboundOrderResponseDataInboundOrdersMerchant } from './GetInboundOrderResponseDataInboundOrdersMerchant';
import { Fbt202602GetInboundOrderResponseDataInboundOrdersStatusLogs } from './GetInboundOrderResponseDataInboundOrdersStatusLogs';
import { Fbt202602GetInboundOrderResponseDataInboundOrdersWarehouse } from './GetInboundOrderResponseDataInboundOrdersWarehouse';

export class Fbt202602GetInboundOrderResponseDataInboundOrders {
    /**
    * Unix seconds timestamp of the actual arrival time of the inbound order.
    */
    'actualArrivalTime'?: number;
    /**
    * Detailed carton information for the inbound order. Only populated if `include_carton_detail` is passed as true in the request.
    */
    'cartonDetails'?: Array<Fbt202602GetInboundOrderResponseDataInboundOrdersCartonDetails>;
    /**
    * Unix seconds timestamp when the inbound order was created.
    */
    'createTime'?: number;
    /**
    * Unix seconds timestamp of the expected arrival time provided by merchant.
    */
    'expectedArrivalTime'?: number;
    /**
    * A detailed breakdown of planned versus actual receiving information, segmented by item, lot number, and expiration date.
    */
    'inboundGoodsLotReceiveItemDetails'?: Array<Fbt202602GetInboundOrderResponseDataInboundOrdersInboundGoodsLotReceiveItemDetails>;
    /**
    * List of logistics information tied to the order. Only populated for small-parcel inbound orders.
    */
    'logisticInfoList'?: Array<Fbt202602GetInboundOrderResponseDataInboundOrdersLogisticInfoList>;
    'merchant'?: Fbt202602GetInboundOrderResponseDataInboundOrdersMerchant;
    /**
    * The numeric identifier for inbound order in Fulfilled by TikTok system.
    */
    'orderId'?: string;
    /**
    * The string identifier for inbound order in Fulfilled by TikTok system.
    */
    'orderIdString'?: string;
    /**
    * Plan identifier for the inbound order.
    */
    'orderPlanId'?: string;
    /**
    * Unix seconds timestamp when the inbound order was shipped.
    */
    'shipTime'?: number;
    /**
    * A list of inbound order operation history.
    */
    'statusLogs'?: Array<Fbt202602GetInboundOrderResponseDataInboundOrdersStatusLogs>;
    'warehouse'?: Fbt202602GetInboundOrderResponseDataInboundOrdersWarehouse;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "actualArrivalTime",
            "baseName": "actual_arrival_time",
            "type": "number"
        },
        {
            "name": "cartonDetails",
            "baseName": "carton_details",
            "type": "Array<Fbt202602GetInboundOrderResponseDataInboundOrdersCartonDetails>"
        },
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "number"
        },
        {
            "name": "expectedArrivalTime",
            "baseName": "expected_arrival_time",
            "type": "number"
        },
        {
            "name": "inboundGoodsLotReceiveItemDetails",
            "baseName": "inbound_goods_lot_receive_item_details",
            "type": "Array<Fbt202602GetInboundOrderResponseDataInboundOrdersInboundGoodsLotReceiveItemDetails>"
        },
        {
            "name": "logisticInfoList",
            "baseName": "logistic_info_list",
            "type": "Array<Fbt202602GetInboundOrderResponseDataInboundOrdersLogisticInfoList>"
        },
        {
            "name": "merchant",
            "baseName": "merchant",
            "type": "Fbt202602GetInboundOrderResponseDataInboundOrdersMerchant"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        },
        {
            "name": "orderIdString",
            "baseName": "order_id_string",
            "type": "string"
        },
        {
            "name": "orderPlanId",
            "baseName": "order_plan_id",
            "type": "string"
        },
        {
            "name": "shipTime",
            "baseName": "ship_time",
            "type": "number"
        },
        {
            "name": "statusLogs",
            "baseName": "status_logs",
            "type": "Array<Fbt202602GetInboundOrderResponseDataInboundOrdersStatusLogs>"
        },
        {
            "name": "warehouse",
            "baseName": "warehouse",
            "type": "Fbt202602GetInboundOrderResponseDataInboundOrdersWarehouse"
        }    ];

    static getAttributeTypeMap() {
        return Fbt202602GetInboundOrderResponseDataInboundOrders.attributeTypeMap;
    }
}

