/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Fbt202602GetInboundMethodDetailResponseDataInfoAllocationShipmentsCartons } from './GetInboundMethodDetailResponseDataInfoAllocationShipmentsCartons';
import { Fbt202602GetInboundMethodDetailResponseDataInfoAllocationShipmentsGoodsItems } from './GetInboundMethodDetailResponseDataInfoAllocationShipmentsGoodsItems';
import { Fbt202602GetInboundMethodDetailResponseDataInfoAllocationShipmentsShipmentOptions } from './GetInboundMethodDetailResponseDataInfoAllocationShipmentsShipmentOptions';

export class Fbt202602GetInboundMethodDetailResponseDataInfoAllocationShipments {
    /**
    * Carton List.
    */
    'cartons'?: Array<Fbt202602GetInboundMethodDetailResponseDataInfoAllocationShipmentsCartons>;
    /**
    * Goods item list.
    */
    'goodsItems'?: Array<Fbt202602GetInboundMethodDetailResponseDataInfoAllocationShipmentsGoodsItems>;
    /**
    * Shipment options.
    */
    'shipmentOptions'?: Array<Fbt202602GetInboundMethodDetailResponseDataInfoAllocationShipmentsShipmentOptions>;
    /**
    * Warehouse identifier.
    */
    'warehouseId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cartons",
            "baseName": "cartons",
            "type": "Array<Fbt202602GetInboundMethodDetailResponseDataInfoAllocationShipmentsCartons>"
        },
        {
            "name": "goodsItems",
            "baseName": "goods_items",
            "type": "Array<Fbt202602GetInboundMethodDetailResponseDataInfoAllocationShipmentsGoodsItems>"
        },
        {
            "name": "shipmentOptions",
            "baseName": "shipment_options",
            "type": "Array<Fbt202602GetInboundMethodDetailResponseDataInfoAllocationShipmentsShipmentOptions>"
        },
        {
            "name": "warehouseId",
            "baseName": "warehouse_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Fbt202602GetInboundMethodDetailResponseDataInfoAllocationShipments.attributeTypeMap;
    }
}

