/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Fbt202602ListAvailableInboundMethodResponseDataAvailableInboundMethodListWarehouseList {
    /**
    * warehouse id.
    */
    'warehouseId'?: string;
    /**
    * warehouse name.
    */
    'warehouseName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "warehouseId",
            "baseName": "warehouse_id",
            "type": "string"
        },
        {
            "name": "warehouseName",
            "baseName": "warehouse_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Fbt202602ListAvailableInboundMethodResponseDataAvailableInboundMethodListWarehouseList.attributeTypeMap;
    }
}

