/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Fbt202602PrintLabelRequestBody {
    /**
    * Specifies the layout and dimensions for the generated label PDF. If this parameter is omitted or an invalid value is provided, the system will use the default thermal label format.  **Allowed Values:**  **Standard / Default** * `DEFAULT_40MM_60MM`: Standard 40mm x 60mm thermal label format  **A4 Paper Layouts** * `A4_21UP_60_0MM_40_0MM`: 21-up labels (60.0mm x 40.0mm) on A4 * `A4_21UP_63_5MM_38_1MM`: 21-up labels (63.5mm x 38.1mm) on A4 * `A4_24UP_63_5MM_33_9MM`: 24-up labels (63.5mm x 33.9mm) on A4 * `A4_24UP_64_6MM_33_8MM`: 24-up labels (64.6mm x 33.8mm) on A4 * `A4_24UP_66_0MM_33_9MM`: 24-up labels (66.0mm x 33.9mm) on A4 * `A4_24UP_66_0MM_35_0MM`: 24-up labels (66.0mm x 35.0mm) on A4 * `A4_24UP_70_0MM_36_0MM`: 24-up labels (70.0mm x 36.0mm) on A4 * `A4_24UP_70_0MM_37_0MM`: 24-up labels (70.0mm x 37.0mm) on A4 * `A4_27UP_63_5MM_29_6MM`: 27-up labels (63.5mm x 29.6mm) on A4 * `A4_40UP_52_5MM_29_7MM`: 40-up labels (52.5mm x 29.7mm) on A4 * `A4_44UP_48_5MM_25_4MM`: 44-up labels (48.5mm x 25.4mm) on A4  **US Letter Layouts** * `US_LETTER_30UP_1IN_2_625IN`: 30-up labels (1\" x 2-5/8\") on US Letter  **Note:** If no value is provided, `DEFAULT_40MM_60MM` will be used as the default format.
    */
    'barcodeFormat'?: string;
    /**
    * Specifies the layout and dimensions for the carton labels. If this parameter is omitted or an invalid value is provided, the system will use the default single-label format.  **Allowed Values:**  * `DEFAULT_1UP`: Standard format (1 label per page). * `A4_4UP`: A4 paper format (4 labels per page).  **Note:** If no value is provided, `DEFAULT_1UP` will be used as the default format.
    */
    'cartonLabelFormat'?: string;
    /**
    * The numeric identifier of the inbound order to update tracking information for.   **Note:** Provide the numeric sequence only; do not include the \"IBR\" prefix (e.g., use `123456` instead of `IBR123456`).
    */
    'orderId'?: string;
    /**
    * Specifies the types of documents to be generated in this request. Multiple values can be included to receive a combined output.  **Allowed Values:**  * `CARTON_LABEL`: Identification labels to be stuck on at least two adjacent sides of each carton. * `PACKING_PICKING_LIST`: Warehouse document for identifying and packing items. * `FBT_BARCODE`: Fulfilled by TikTok barcodes.  **Note:** If this list is empty or omitted, `CARTON_LABEL` will be generated by default.
    */
    'printItems'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "barcodeFormat",
            "baseName": "barcode_format",
            "type": "string"
        },
        {
            "name": "cartonLabelFormat",
            "baseName": "carton_label_format",
            "type": "string"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        },
        {
            "name": "printItems",
            "baseName": "print_items",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Fbt202602PrintLabelRequestBody.attributeTypeMap;
    }
}

