/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsCommission {
    /**
    * The commission amount of the product multiplied by 1000, which is equal to floor_price * commission_rate * 1000
    */
    'amount'?: string;
    /**
    * The commission rate of the product multiplied by 10000, eg. 1500 means 15%
    */
    'rate'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "rate",
            "baseName": "rate",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsCommission.attributeTypeMap;
    }
}

