/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateCreator202501CreatorSelectAffiliateProductRequestBodyFilterParams } from './CreatorSelectAffiliateProductRequestBodyFilterParams';
import { AffiliateCreator202501CreatorSelectAffiliateProductRequestBodySortParams } from './CreatorSelectAffiliateProductRequestBodySortParams';

export class AffiliateCreator202501CreatorSelectAffiliateProductRequestBody {
    'filterParams'?: AffiliateCreator202501CreatorSelectAffiliateProductRequestBodyFilterParams;
    'sortParams'?: AffiliateCreator202501CreatorSelectAffiliateProductRequestBodySortParams;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "filterParams",
            "baseName": "filter_params",
            "type": "AffiliateCreator202501CreatorSelectAffiliateProductRequestBodyFilterParams"
        },
        {
            "name": "sortParams",
            "baseName": "sort_params",
            "type": "AffiliateCreator202501CreatorSelectAffiliateProductRequestBodySortParams"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202501CreatorSelectAffiliateProductRequestBody.attributeTypeMap;
    }
}

