/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202309AddShowcaseProductsoldResponseDataErrorsDetail {
    /**
    * The failing product ID when the product is added to the creator\'s showcase
    */
    'productId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309AddShowcaseProductsoldResponseDataErrorsDetail.attributeTypeMap;
    }
}

