/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateCreator202407GenerateAffiliateSharingLinkResponseDataErrorsDetail {
    /**
    * Detail fail reason for specific tag
    */
    'failReason'?: string;
    /**
    * Same as description in request params
    */
    'tag'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "failReason",
            "baseName": "fail_reason",
            "type": "string"
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202407GenerateAffiliateSharingLinkResponseDataErrorsDetail.attributeTypeMap;
    }
}

