/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Promotion202309RemoveActivityProductRequestBody {
    /**
    * IDs of the BXGY benefit products to remove. Max count: 100.
    */
    'benefitProductIds'?: Array<string>;
    /**
    * IDs of the BXGY exclude products to remove. Max count: 100.
    */
    'excludeProductIds'?: Array<string>;
    /**
    * IDs of the products to remove. Max count: 300.
    */
    'productIds'?: Array<string>;
    /**
    * IDs of the SKUs to remove. Max count: 300.
    */
    'skuIds'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "benefitProductIds",
            "baseName": "benefit_product_ids",
            "type": "Array<string>"
        },
        {
            "name": "excludeProductIds",
            "baseName": "exclude_product_ids",
            "type": "Array<string>"
        },
        {
            "name": "productIds",
            "baseName": "product_ids",
            "type": "Array<string>"
        },
        {
            "name": "skuIds",
            "baseName": "sku_ids",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Promotion202309RemoveActivityProductRequestBody.attributeTypeMap;
    }
}

