/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar } from './GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvgCommissionRateRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorAvgCommissionRateRange';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyer } from './GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyer';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyerRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyerRange';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorCategoryGmvDistribution } from './GetMarketplaceCreatorPerformanceResponseDataCreatorCategoryGmvDistribution';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorContentGmvDistribution } from './GetMarketplaceCreatorPerformanceResponseDataCreatorContentGmvDistribution';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGmv } from './GetMarketplaceCreatorPerformanceResponseDataCreatorGmv';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGmvRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorGmvRange';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGpm } from './GetMarketplaceCreatorPerformanceResponseDataCreatorGpm';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGmv } from './GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGmv';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpm } from './GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpm';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpmRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpmRange';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorProductOriginalPriceRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorProductOriginalPriceRange';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorUnitsSoldRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorUnitsSoldRange';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGmv } from './GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGmv';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpm } from './GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpm';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpmRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpmRange';

export class AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreator {
    'avatar'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar;
    /**
    * The average commission rate in hundredths of a percent. Note that if the creator has not given permission for precise data sharing, these properties will not be present.
    */
    'avgCommissionRate'?: number;
    'avgCommissionRateRange'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvgCommissionRateRange;
    /**
    * Average e-commerce live stream comments.
    */
    'avgEcLiveCommentCount'?: number;
    /**
    * Average e-commerce live stream likes.
    */
    'avgEcLiveLikeCount'?: number;
    /**
    * Average e-commerce live stream shares.
    */
    'avgEcLiveShareCount'?: number;
    /**
    * Average live stream views with promoted products.
    */
    'avgEcLiveViewCount'?: number;
    /**
    * Average e-commerce video comments.
    */
    'avgEcVideoCommentCount'?: number;
    /**
    * Average e-commerce video likes.
    */
    'avgEcVideoLikeCount'?: number;
    /**
    * The average number of number of e-commerce video plays. 
    */
    'avgEcVideoPlayCount'?: number;
    /**
    * Average e-commerce video shares.
    */
    'avgEcVideoShareCount'?: number;
    'avgGmvPerBuyer'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyer;
    'avgGmvPerBuyerRange'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyerRange;
    /**
    * The biography description associated with the creator.
    */
    'bioDescription'?: string;
    /**
    * The total number of brands with which the creator has previously collaborated.
    */
    'brandCollaborationCount'?: number;
    /**
    * GMV distribution by category.
    */
    'categoryGmvDistribution'?: Array<AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorCategoryGmvDistribution>;
    /**
    * A list of category identifiers associated with the products for which the creator has created posts. 
    */
    'categoryIds'?: Array<string>;
    /**
    * GMV associated with creator content by content type.
    */
    'contentGmvDistribution'?: Array<AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorContentGmvDistribution>;
    /**
    * The number of e-commerce livestreams associated with the creator.
    */
    'ecLiveCount'?: number;
    /**
    * E-commerce live stream engagement rate in hundredths of a percent. For example, `6000` is 60%.
    */
    'ecLiveEngagementRate'?: string;
    /**
    * The number of e-commerce video posts associated with the creator.
    */
    'ecVideoCount'?: number;
    /**
    * The creator\'s follower count.
    */
    'followerCount'?: number;
    'gmv'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGmv;
    'gmvRange'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGmvRange;
    'gpm'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGpm;
    'gpmRange'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange;
    'liveGmv'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGmv;
    'liveGpm'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpm;
    'liveGpmRange'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpmRange;
    /**
    * TikTok nickname.
    */
    'nickname'?: string;
    'productOriginalPriceRange'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorProductOriginalPriceRange;
    /**
    * The URL for the creator\'s TikTok profile page.
    */
    'profileTtUri'?: string;
    /**
    * The number of promoted products associated with the creator. 
    */
    'promotedProductNum'?: number;
    /**
    * The region associated with the creator.
    */
    'selectionRegion'?: string;
    /**
    * A list of the top 10 brands with which the creator has previously collaborated.
    */
    'topCollaboratedBrandIds'?: Array<string>;
    /**
    * The total number of units sold. Units are indexed to SKU. Note that if the creator has not given permission for precise data sharing, this property will not be present.
    */
    'unitsSold'?: number;
    'unitsSoldRange'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorUnitsSoldRange;
    /**
    * TikTok user name.
    */
    'username'?: string;
    'videoGmv'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGmv;
    'videoGpm'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpm;
    'videoGpmRange'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpmRange;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar"
        },
        {
            "name": "avgCommissionRate",
            "baseName": "avg_commission_rate",
            "type": "number"
        },
        {
            "name": "avgCommissionRateRange",
            "baseName": "avg_commission_rate_range",
            "type": "AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvgCommissionRateRange"
        },
        {
            "name": "avgEcLiveCommentCount",
            "baseName": "avg_ec_live_comment_count",
            "type": "number"
        },
        {
            "name": "avgEcLiveLikeCount",
            "baseName": "avg_ec_live_like_count",
            "type": "number"
        },
        {
            "name": "avgEcLiveShareCount",
            "baseName": "avg_ec_live_share_count",
            "type": "number"
        },
        {
            "name": "avgEcLiveViewCount",
            "baseName": "avg_ec_live_view_count",
            "type": "number"
        },
        {
            "name": "avgEcVideoCommentCount",
            "baseName": "avg_ec_video_comment_count",
            "type": "number"
        },
        {
            "name": "avgEcVideoLikeCount",
            "baseName": "avg_ec_video_like_count",
            "type": "number"
        },
        {
            "name": "avgEcVideoPlayCount",
            "baseName": "avg_ec_video_play_count",
            "type": "number"
        },
        {
            "name": "avgEcVideoShareCount",
            "baseName": "avg_ec_video_share_count",
            "type": "number"
        },
        {
            "name": "avgGmvPerBuyer",
            "baseName": "avg_gmv_per_buyer",
            "type": "AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyer"
        },
        {
            "name": "avgGmvPerBuyerRange",
            "baseName": "avg_gmv_per_buyer_range",
            "type": "AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyerRange"
        },
        {
            "name": "bioDescription",
            "baseName": "bio_description",
            "type": "string"
        },
        {
            "name": "brandCollaborationCount",
            "baseName": "brand_collaboration_count",
            "type": "number"
        },
        {
            "name": "categoryGmvDistribution",
            "baseName": "category_gmv_distribution",
            "type": "Array<AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorCategoryGmvDistribution>"
        },
        {
            "name": "categoryIds",
            "baseName": "category_ids",
            "type": "Array<string>"
        },
        {
            "name": "contentGmvDistribution",
            "baseName": "content_gmv_distribution",
            "type": "Array<AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorContentGmvDistribution>"
        },
        {
            "name": "ecLiveCount",
            "baseName": "ec_live_count",
            "type": "number"
        },
        {
            "name": "ecLiveEngagementRate",
            "baseName": "ec_live_engagement_rate",
            "type": "string"
        },
        {
            "name": "ecVideoCount",
            "baseName": "ec_video_count",
            "type": "number"
        },
        {
            "name": "followerCount",
            "baseName": "follower_count",
            "type": "number"
        },
        {
            "name": "gmv",
            "baseName": "gmv",
            "type": "AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGmv"
        },
        {
            "name": "gmvRange",
            "baseName": "gmv_range",
            "type": "AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGmvRange"
        },
        {
            "name": "gpm",
            "baseName": "gpm",
            "type": "AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGpm"
        },
        {
            "name": "gpmRange",
            "baseName": "gpm_range",
            "type": "AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange"
        },
        {
            "name": "liveGmv",
            "baseName": "live_gmv",
            "type": "AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGmv"
        },
        {
            "name": "liveGpm",
            "baseName": "live_gpm",
            "type": "AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpm"
        },
        {
            "name": "liveGpmRange",
            "baseName": "live_gpm_range",
            "type": "AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpmRange"
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string"
        },
        {
            "name": "productOriginalPriceRange",
            "baseName": "product_original_price_range",
            "type": "AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorProductOriginalPriceRange"
        },
        {
            "name": "profileTtUri",
            "baseName": "profile_tt_uri",
            "type": "string"
        },
        {
            "name": "promotedProductNum",
            "baseName": "promoted_product_num",
            "type": "number"
        },
        {
            "name": "selectionRegion",
            "baseName": "selection_region",
            "type": "string"
        },
        {
            "name": "topCollaboratedBrandIds",
            "baseName": "top_collaborated_brand_ids",
            "type": "Array<string>"
        },
        {
            "name": "unitsSold",
            "baseName": "units_sold",
            "type": "number"
        },
        {
            "name": "unitsSoldRange",
            "baseName": "units_sold_range",
            "type": "AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorUnitsSoldRange"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        },
        {
            "name": "videoGmv",
            "baseName": "video_gmv",
            "type": "AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGmv"
        },
        {
            "name": "videoGpm",
            "baseName": "video_gpm",
            "type": "AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpm"
        },
        {
            "name": "videoGpmRange",
            "baseName": "video_gpm_range",
            "type": "AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpmRange"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreator.attributeTypeMap;
    }
}

