/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpmRange {
    /**
    * The currency code.
    */
    'currency'?: string;
    /**
    * The formatted range of livestream GPM values associted with the creator. 
    */
    'formattedRange'?: string;
    /**
    * The highest livestream GPM value.
    */
    'maximumAmount'?: string;
    /**
    * The lowest livestream GPM value.
    */
    'minimumAmount'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "formattedRange",
            "baseName": "formatted_range",
            "type": "string"
        },
        {
            "name": "maximumAmount",
            "baseName": "maximum_amount",
            "type": "string"
        },
        {
            "name": "minimumAmount",
            "baseName": "minimum_amount",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpmRange.attributeTypeMap;
    }
}

