/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202505SellerSearchCreatoronMarketplaceResponseDataCreators } from './SellerSearchCreatoronMarketplaceResponseDataCreators';

export class AffiliateSeller202505SellerSearchCreatoronMarketplaceResponseData {
    /**
    * Creator\'s basic information
    */
    'creators'?: Array<AffiliateSeller202505SellerSearchCreatoronMarketplaceResponseDataCreators>;
    /**
    * Next page token
    */
    'nextPageToken'?: string;
    /**
    * Caching search results improves api performance and ensures stable request results
    */
    'searchKey'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "creators",
            "baseName": "creators",
            "type": "Array<AffiliateSeller202505SellerSearchCreatoronMarketplaceResponseDataCreators>"
        },
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "searchKey",
            "baseName": "search_key",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202505SellerSearchCreatoronMarketplaceResponseData.attributeTypeMap;
    }
}

