/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Fbt202601CancelFBTMCFOrderRequestBodyConsignOrders } from './CancelFBTMCFOrderRequestBodyConsignOrders';

export class Fbt202601CancelFBTMCFOrderRequestBody {
    /**
    * The cancel list of consign order
    */
    'consignOrders'?: Array<Fbt202601CancelFBTMCFOrderRequestBodyConsignOrders>;
    /**
    * A unique ID that identifies different MCF orders
    */
    'mcfOrderId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "consignOrders",
            "baseName": "consign_orders",
            "type": "Array<Fbt202601CancelFBTMCFOrderRequestBodyConsignOrders>"
        },
        {
            "name": "mcfOrderId",
            "baseName": "mcf_order_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Fbt202601CancelFBTMCFOrderRequestBody.attributeTypeMap;
    }
}

