/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Fbt202601CreateFBTMCFOrderRequestBodyConsignee } from './CreateFBTMCFOrderRequestBodyConsignee';
import { Fbt202601CreateFBTMCFOrderRequestBodyGoods } from './CreateFBTMCFOrderRequestBodyGoods';

export class Fbt202601CreateFBTMCFOrderRequestBody {
    'consignee'?: Fbt202601CreateFBTMCFOrderRequestBodyConsignee;
    /**
    * The corresponding order ID in your OMS.
    */
    'externalOrderId'?: string;
    /**
    * The item IDs and quantities included in the order, where the items must be those managed in the FBT system. 
    */
    'goods'?: Array<Fbt202601CreateFBTMCFOrderRequestBodyGoods>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "consignee",
            "baseName": "consignee",
            "type": "Fbt202601CreateFBTMCFOrderRequestBodyConsignee"
        },
        {
            "name": "externalOrderId",
            "baseName": "external_order_id",
            "type": "string"
        },
        {
            "name": "goods",
            "baseName": "goods",
            "type": "Array<Fbt202601CreateFBTMCFOrderRequestBodyGoods>"
        }    ];

    static getAttributeTypeMap() {
        return Fbt202601CreateFBTMCFOrderRequestBody.attributeTypeMap;
    }
}

