/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Fbt202601GetFBFMCFOrderStatusResponseDataMcfOrderConsignOrders } from './GetFBFMCFOrderStatusResponseDataMcfOrderConsignOrders';

export class Fbt202601GetFBFMCFOrderStatusResponseDataMcfOrder {
    /**
    * Once the order has been shipped, the `consign_orders` field will display the consignment details of the order.
    */
    'consignOrders'?: Array<Fbt202601GetFBFMCFOrderStatusResponseDataMcfOrderConsignOrders>;
    /**
    * The time when the mcf order is created
    */
    'createTime'?: number;
    /**
    * The corresponding order ID in your OMS.
    */
    'externalOrderId'?: string;
    /**
    * A unique ID that identifies different MCF orders
    */
    'mcfOrderId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "consignOrders",
            "baseName": "consign_orders",
            "type": "Array<Fbt202601GetFBFMCFOrderStatusResponseDataMcfOrderConsignOrders>"
        },
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "number"
        },
        {
            "name": "externalOrderId",
            "baseName": "external_order_id",
            "type": "string"
        },
        {
            "name": "mcfOrderId",
            "baseName": "mcf_order_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Fbt202601GetFBFMCFOrderStatusResponseDataMcfOrder.attributeTypeMap;
    }
}

