/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Fbt202601GetFBFMCFOrderStatusResponseDataMcfOrderConsignOrdersGoods {
    /**
    * Identifier for goods generated by Fulfilled by TikTok systemgoods id
    */
    'id'?: string;
    /**
    * The goods quantity in this consign order
    */
    'quantity'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Fbt202601GetFBFMCFOrderStatusResponseDataMcfOrderConsignOrdersGoods.attributeTypeMap;
    }
}

