/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Fbt202601QueryGoodsInventoryForMCFRequestBodyGoods {
    /**
    * The identifiers for goods generated by Fulfilled by TikTok system.
    */
    'goodsId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "goodsId",
            "baseName": "goods_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Fbt202601QueryGoodsInventoryForMCFRequestBodyGoods.attributeTypeMap;
    }
}

