/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202511GetBestsellingVideosResponseDataVideosProductInfos {
    /**
    * Product ID lists in product anchors. Exclude deactivated and soldout products.
    */
    'productId'?: string;
    /**
    * Product name list of product anchors. Exclude deactivated and soldout products.
    */
    'productName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        },
        {
            "name": "productName",
            "baseName": "product_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202511GetBestsellingVideosResponseDataVideosProductInfos.attributeTypeMap;
    }
}

