/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202511GetBestsellingLIVEsResponseDataLives {
    /**
    * The creator’s unique username used for system identification.
    */
    'creatorName'?: string;
    /**
    * The creator’s display nickname, visible externally.
    */
    'creatorNickName'?: string;
    /**
    * LVIE session duration, in seconds
    */
    'duration'?: number;
    /**
    * Gmv Range
    */
    'gmvRange'?: string;
    /**
    * LIVE session id
    */
    'id'?: string;
    /**
    * The creator’s unique ID, uniquely identifying the creator in the system.
    */
    'openId'?: string;
    /**
    * GMV rank of the LIVE session
    */
    'rank'?: number;
    /**
    * Start time of the LIVE, unix timestamp GMT (UTC+00:00).
    */
    'startTime'?: number;
    /**
    * LIVE session  title
    */
    'title'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "creatorName",
            "baseName": "creator_name",
            "type": "string"
        },
        {
            "name": "creatorNickName",
            "baseName": "creator_nick_name",
            "type": "string"
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "number"
        },
        {
            "name": "gmvRange",
            "baseName": "gmv_range",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "openId",
            "baseName": "open_id",
            "type": "string"
        },
        {
            "name": "rank",
            "baseName": "rank",
            "type": "number"
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "number"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202511GetBestsellingLIVEsResponseDataLives.attributeTypeMap;
    }
}

