/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202602SearchReturnsResponseDataReturnOrdersReturnLineItemsProductImage } from './SearchReturnsResponseDataReturnOrdersReturnLineItemsProductImage';
import { ReturnRefund202602SearchReturnsResponseDataReturnOrdersReturnLineItemsRefundAmount } from './SearchReturnsResponseDataReturnOrdersReturnLineItemsRefundAmount';
import { ReturnRefund202602SearchReturnsResponseDataReturnOrdersReturnLineItemsReturnSubLineItems } from './SearchReturnsResponseDataReturnOrdersReturnLineItemsReturnSubLineItems';

export class ReturnRefund202602SearchReturnsResponseDataReturnOrdersReturnLineItems {
    /**
    * Order line ID.
    */
    'orderLineItemId'?: string;
    'productImage'?: ReturnRefund202602SearchReturnsResponseDataReturnOrdersReturnLineItemsProductImage;
    /**
    * Product name.
    */
    'productName'?: string;
    'refundAmount'?: ReturnRefund202602SearchReturnsResponseDataReturnOrdersReturnLineItemsRefundAmount;
    /**
    * Return order line ID.
    */
    'returnLineItemId'?: string;
    /**
    * Return sub order lines items. Sub items represent skus that belong to a \"virtual bundle\" that has been defined by a seller. The sub_items will include all relevant information about each item that is a part of the virtual bundle.
    */
    'returnSubLineItems'?: Array<ReturnRefund202602SearchReturnsResponseDataReturnOrdersReturnLineItemsReturnSubLineItems>;
    /**
    * SKU name defined by seller.
    */
    'sellerSku'?: string;
    /**
    * SKU ID.
    */
    'skuId'?: string;
    /**
    * SKU name.
    */
    'skuName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderLineItemId",
            "baseName": "order_line_item_id",
            "type": "string"
        },
        {
            "name": "productImage",
            "baseName": "product_image",
            "type": "ReturnRefund202602SearchReturnsResponseDataReturnOrdersReturnLineItemsProductImage"
        },
        {
            "name": "productName",
            "baseName": "product_name",
            "type": "string"
        },
        {
            "name": "refundAmount",
            "baseName": "refund_amount",
            "type": "ReturnRefund202602SearchReturnsResponseDataReturnOrdersReturnLineItemsRefundAmount"
        },
        {
            "name": "returnLineItemId",
            "baseName": "return_line_item_id",
            "type": "string"
        },
        {
            "name": "returnSubLineItems",
            "baseName": "return_sub_line_items",
            "type": "Array<ReturnRefund202602SearchReturnsResponseDataReturnOrdersReturnLineItemsReturnSubLineItems>"
        },
        {
            "name": "sellerSku",
            "baseName": "seller_sku",
            "type": "string"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        },
        {
            "name": "skuName",
            "baseName": "sku_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202602SearchReturnsResponseDataReturnOrdersReturnLineItems.attributeTypeMap;
    }
}

