/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202602SearchCancellationsResponseDataCancellationsCancelLineItemsCancelSubLineItemsProductImage } from './SearchCancellationsResponseDataCancellationsCancelLineItemsCancelSubLineItemsProductImage';
import { ReturnRefund202602SearchCancellationsResponseDataCancellationsCancelLineItemsCancelSubLineItemsRefundAmount } from './SearchCancellationsResponseDataCancellationsCancelLineItemsCancelSubLineItemsRefundAmount';

export class ReturnRefund202602SearchCancellationsResponseDataCancellationsCancelLineItemsCancelSubLineItems {
    /**
    * Cancellation line item ID.
    */
    'cancelLineItemId'?: string;
    /**
    * Cancellation sub line item ID.
    */
    'cancelSubLineItemId'?: string;
    /**
    * Order line item ID.
    */
    'orderLineItemId'?: string;
    'productImage'?: ReturnRefund202602SearchCancellationsResponseDataCancellationsCancelLineItemsCancelSubLineItemsProductImage;
    /**
    * Product name.
    */
    'productName'?: string;
    'refundAmount'?: ReturnRefund202602SearchCancellationsResponseDataCancellationsCancelLineItemsCancelSubLineItemsRefundAmount;
    /**
    * SKU name defined by the seller.
    */
    'sellerSku'?: string;
    /**
    * SKU ID.
    */
    'skuId'?: string;
    /**
    * SKU name.
    */
    'skuName'?: string;
    /**
    * Sub Order line item ID.
    */
    'subOrderLineItemId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cancelLineItemId",
            "baseName": "cancel_line_item_id",
            "type": "string"
        },
        {
            "name": "cancelSubLineItemId",
            "baseName": "cancel_sub_line_item_id",
            "type": "string"
        },
        {
            "name": "orderLineItemId",
            "baseName": "order_line_item_id",
            "type": "string"
        },
        {
            "name": "productImage",
            "baseName": "product_image",
            "type": "ReturnRefund202602SearchCancellationsResponseDataCancellationsCancelLineItemsCancelSubLineItemsProductImage"
        },
        {
            "name": "productName",
            "baseName": "product_name",
            "type": "string"
        },
        {
            "name": "refundAmount",
            "baseName": "refund_amount",
            "type": "ReturnRefund202602SearchCancellationsResponseDataCancellationsCancelLineItemsCancelSubLineItemsRefundAmount"
        },
        {
            "name": "sellerSku",
            "baseName": "seller_sku",
            "type": "string"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        },
        {
            "name": "skuName",
            "baseName": "sku_name",
            "type": "string"
        },
        {
            "name": "subOrderLineItemId",
            "baseName": "sub_order_line_item_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202602SearchCancellationsResponseDataCancellationsCancelLineItemsCancelSubLineItems.attributeTypeMap;
    }
}

