/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202601ProductAuditingResearchRequestBody {
    /**
    * The ID of the brand of this product.
    */
    'brandIds'?: Array<string>;
    /**
    * The category id of the source product included in the virtual bundle.
    */
    'categoryIds'?: Array<string>;
    /**
    * The product ID generated by TikTok Shop. Max is 20
    */
    'productIds'?: Array<string>;
    /**
    * The product title.  Title length: - DE, ES, FR, IE, IT, JP, UK, US: [1, 255]  - BR, MX: [1, 300]  - Other regions: [25, 255]
    */
    'productTitle'?: string;
    /**
    * The Shop identity ID.
    */
    'sellerId'?: string;
    /**
    * The name of the shop which product belongs to.
    */
    'sellerName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "brandIds",
            "baseName": "brand_ids",
            "type": "Array<string>"
        },
        {
            "name": "categoryIds",
            "baseName": "category_ids",
            "type": "Array<string>"
        },
        {
            "name": "productIds",
            "baseName": "product_ids",
            "type": "Array<string>"
        },
        {
            "name": "productTitle",
            "baseName": "product_title",
            "type": "string"
        },
        {
            "name": "sellerId",
            "baseName": "seller_id",
            "type": "string"
        },
        {
            "name": "sellerName",
            "baseName": "seller_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202601ProductAuditingResearchRequestBody.attributeTypeMap;
    }
}

