/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202510GetShopPerformancePerHourResponseDataPerformance } from './GetShopPerformancePerHourResponseDataPerformance';

export class Analytics202510GetShopPerformancePerHourResponseData {
    'performance'?: Analytics202510GetShopPerformancePerHourResponseDataPerformance;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "performance",
            "baseName": "performance",
            "type": "Analytics202510GetShopPerformancePerHourResponseDataPerformance"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202510GetShopPerformancePerHourResponseData.attributeTypeMap;
    }
}

