/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202510GetShopLIVEPerformancePerMinutesResponseDataPerformanceOverallGmv } from './GetShopLIVEPerformancePerMinutesResponseDataPerformanceOverallGmv';

export class Analytics202510GetShopLIVEPerformancePerMinutesResponseDataPerformanceOverall {
    /**
    * LIVE session duration in seconds
    */
    'duration'?: number;
    /**
    * End time of the LIVE, unix timestamp GMT (UTC+00:00).
    */
    'endTime'?: number;
    'gmv'?: Analytics202510GetShopLIVEPerformancePerMinutesResponseDataPerformanceOverallGmv;
    /**
    * The total number of times the LIVE was displayed to viewers.
    */
    'impressions'?: number;
    /**
    * The number of items sold directly from the LIVE.
    */
    'itemsSold'?: number;
    /**
    * LIVE session title
    */
    'liveTitle'?: string;
    /**
    * Start time of the LIVE, unix timestamp GMT (UTC+00:00).
    */
    'startTime'?: number;
    /**
    * The number of unique viewers in the LIVE room.
    */
    'uniqueViewers'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "duration",
            "baseName": "duration",
            "type": "number"
        },
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "number"
        },
        {
            "name": "gmv",
            "baseName": "gmv",
            "type": "Analytics202510GetShopLIVEPerformancePerMinutesResponseDataPerformanceOverallGmv"
        },
        {
            "name": "impressions",
            "baseName": "impressions",
            "type": "number"
        },
        {
            "name": "itemsSold",
            "baseName": "items_sold",
            "type": "number"
        },
        {
            "name": "liveTitle",
            "baseName": "live_title",
            "type": "string"
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "number"
        },
        {
            "name": "uniqueViewers",
            "baseName": "unique_viewers",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202510GetShopLIVEPerformancePerMinutesResponseDataPerformanceOverall.attributeTypeMap;
    }
}

