/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateCreator202601GetShoppableVideoPrecheckResultResponseDataPrecheckTaskGoodQualityCheckResult } from './GetShoppableVideoPrecheckResultResponseDataPrecheckTaskGoodQualityCheckResult';
import { AffiliateCreator202601GetShoppableVideoPrecheckResultResponseDataPrecheckTaskViolationCheckResult } from './GetShoppableVideoPrecheckResultResponseDataPrecheckTaskViolationCheckResult';

export class AffiliateCreator202601GetShoppableVideoPrecheckResultResponseDataPrecheckTask {
    'goodQualityCheckResult'?: AffiliateCreator202601GetShoppableVideoPrecheckResultResponseDataPrecheckTaskGoodQualityCheckResult;
    /**
    * The id of the video pre-check task.
    */
    'id'?: string;
    'violationCheckResult'?: AffiliateCreator202601GetShoppableVideoPrecheckResultResponseDataPrecheckTaskViolationCheckResult;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "goodQualityCheckResult",
            "baseName": "good_quality_check_result",
            "type": "AffiliateCreator202601GetShoppableVideoPrecheckResultResponseDataPrecheckTaskGoodQualityCheckResult"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "violationCheckResult",
            "baseName": "violation_check_result",
            "type": "AffiliateCreator202601GetShoppableVideoPrecheckResultResponseDataPrecheckTaskViolationCheckResult"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202601GetShoppableVideoPrecheckResultResponseDataPrecheckTask.attributeTypeMap;
    }
}

