/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateCreator202601GetShopCategoryAndCollectionResponseDataGroups } from './GetShopCategoryAndCollectionResponseDataGroups';

export class AffiliateCreator202601GetShopCategoryAndCollectionResponseData {
    /**
    * Group info
    */
    'groups'?: Array<AffiliateCreator202601GetShopCategoryAndCollectionResponseDataGroups>;
    /**
    * next page number
    */
    'nextPage'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "groups",
            "baseName": "groups",
            "type": "Array<AffiliateCreator202601GetShopCategoryAndCollectionResponseDataGroups>"
        },
        {
            "name": "nextPage",
            "baseName": "next_page",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202601GetShopCategoryAndCollectionResponseData.attributeTypeMap;
    }
}

