/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Fulfillment202408CreateLastMileBundleRequestBodyLastMileBundleDimensions } from './CreateLastMileBundleRequestBodyLastMileBundleDimensions';
import { Fulfillment202408CreateLastMileBundleRequestBodyLastMileBundleWeight } from './CreateLastMileBundleRequestBodyLastMileBundleWeight';

export class Fulfillment202408CreateLastMileBundleRequestBodyLastMileBundle {
    'dimensions'?: Fulfillment202408CreateLastMileBundleRequestBodyLastMileBundleDimensions;
    /**
    * Bundle ID in your order management system
    */
    'externalBundleId'?: string;
    /**
    * Number of small packages in the bundle
    */
    'fulfillmentUnitCount'?: number;
    /**
    * UNIX timestamp of outbounding from your warehouse in milliseconds.
    */
    'outboundTime'?: number;
    'weight'?: Fulfillment202408CreateLastMileBundleRequestBodyLastMileBundleWeight;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dimensions",
            "baseName": "dimensions",
            "type": "Fulfillment202408CreateLastMileBundleRequestBodyLastMileBundleDimensions"
        },
        {
            "name": "externalBundleId",
            "baseName": "external_bundle_id",
            "type": "string"
        },
        {
            "name": "fulfillmentUnitCount",
            "baseName": "fulfillment_unit_count",
            "type": "number"
        },
        {
            "name": "outboundTime",
            "baseName": "outbound_time",
            "type": "number"
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "Fulfillment202408CreateLastMileBundleRequestBodyLastMileBundleWeight"
        }    ];

    static getAttributeTypeMap() {
        return Fulfillment202408CreateLastMileBundleRequestBodyLastMileBundle.attributeTypeMap;
    }
}

