/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Fulfillment202408CreateLastMileBundleRequestBodyLastMileBundleDimensions {
    /**
    * Height value
    */
    'height'?: number;
    /**
    * Length value
    */
    'length'?: number;
    /**
    * Unit. Possible enumerations: - `centimeter`.
    */
    'unit'?: string;
    /**
    * Width value
    */
    'width'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Fulfillment202408CreateLastMileBundleRequestBodyLastMileBundleDimensions.attributeTypeMap;
    }
}

