/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202406SellerSearchCreatoronMarketplaceRequestBodyFollowerDemographicsCountRange {
    /**
    * The minimum value of follower count.  The value passed in must be greater than or equal to 0
    */
    'countGe'?: number;
    /**
    * The maximum value of follower count.  - Generally, a value greater than or equal to 0 needs to be passed. If a value less than 0 is passed, it means that the field will not be filtered.
    */
    'countLe'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "countGe",
            "baseName": "count_ge",
            "type": "number"
        },
        {
            "name": "countLe",
            "baseName": "count_le",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202406SellerSearchCreatoronMarketplaceRequestBodyFollowerDemographicsCountRange.attributeTypeMap;
    }
}

