/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorFollowerLocation {
    /**
    * The location, use [TWO-LETTER STATE AND TERRITORY ABBREVIATIONS](https://www.faa.gov/air_traffic/publications/atpubs/cnt_html/appendix_a.html)
    */
    'key'?: string;
    /**
    * The proportion of followers from this location, expressed as a decimal (e.g., 0.3705 = 37.05%).
    */
    'value'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202508GetMarketplaceCreatorPerformanceResponseDataCreatorFollowerLocation.attributeTypeMap;
    }
}

