/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202508SellerSearchCreatoronMarketplaceRequestBodyContentPerformance {
    /**
    * Average engagement rate more than 0-20. You can only filter by increments of 1% point, up to 20%. 
    */
    'avgEngagementRate'?: string;
    /**
    * Average LIVE views greater than or equal to Pick any whole number between 0 and 100,000, and we will return all results with average video views greater than that number. You can only pass in average LIVE or average shoppable LIVE. Using both filters will cause the API call to fail
    */
    'avgLiveAvgViewersGe'?: string;
    /**
    * Average shoppable engagement rate more than 0-20. You can only filter by increments of 1% point, up to 20%. 
    */
    'avgShopableEngagementRate'?: string;
    /**
    * Average shoppable LIVE viewers greater than or equal to Pick any whole number between 0 and 100,000, and we will return all results with average video views greater than that number. You can only pass in average LIVE or average shoppable LIVE. Using both filters will cause the API call to fail
    */
    'avgShoppableLiveAvgViewersGe'?: string;
    /**
    * You can pass in average shoppable video views anywhere between 0 and 100k Pick any whole number between 0 and 100,000, and we will return all results with average shoppable video views greater than that number. You can only pass in Average Video Views OR Average Shoppable Video Views. Using both filters will cause the API call to fail.
    */
    'avgShoppableVideoViews'?: string;
    /**
    * Average Video Views more than You can pass in average video views anywhere between 0 and 100k Pick any whole number between 0 and 100,000, and we will return all results with average video views greater than that number. You can only pass in Average Video Views OR Average Shoppable Video Views. Using both filters will cause the API call to fail.
    */
    'avgVideoViews'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avgEngagementRate",
            "baseName": "avg_engagement_rate",
            "type": "string"
        },
        {
            "name": "avgLiveAvgViewersGe",
            "baseName": "avg_live_avg_viewers_ge",
            "type": "string"
        },
        {
            "name": "avgShopableEngagementRate",
            "baseName": "avg_shopable_engagement_rate",
            "type": "string"
        },
        {
            "name": "avgShoppableLiveAvgViewersGe",
            "baseName": "avg_shoppable_live_avg_viewers_ge",
            "type": "string"
        },
        {
            "name": "avgShoppableVideoViews",
            "baseName": "avg_shoppable_video_views",
            "type": "string"
        },
        {
            "name": "avgVideoViews",
            "baseName": "avg_video_views",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202508SellerSearchCreatoronMarketplaceRequestBodyContentPerformance.attributeTypeMap;
    }
}

