/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202508SellerSearchCreatoronMarketplaceRequestBodyAdvancedFilters {
    /**
    * Get the available \"Category Pro\" categories available. Category Pro is a specific label given to Creators that regularly post about one product category and have generated most of their sales in that Category in the past 60 days - Beauty and Self Care - Fashion and Style - Health and Wellness - Home - Men\'s Style - Pet Supplies - Sports and Outdoor - Tech, Office and Books See [Get Seller Search Creator Marketplace Advanced Filters](https://partner.tiktokshop.com/docv2/page/get-seller-search-creator-marketplace-advanced-filters-202601) for the country-specific category pro enums. 
    */
    'categoryPro'?: Array<string>;
    /**
    * Supported creator levels are country/region-specific. Always fetch the valid creator level enums from the Get Seller Search [Creator Marketplace Advanced Filters](https://partner.tiktokshop.com/docv2/page/get-seller-search-creator-marketplace-advanced-filters-202601) endpoint before calling this API.
    */
    'creatorLevel'?: Array<string>;
    /**
    * Supported languages vary by country. If you pass an unsupported language value, the API returns an error. See [Get Seller Search Creator Marketplace Advanced Filters](https://partner.tiktokshop.com/docv2/page/get-seller-search-creator-marketplace-advanced-filters-202601) for the country-specific language enums.
    */
    'language'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "categoryPro",
            "baseName": "category_pro",
            "type": "Array<string>"
        },
        {
            "name": "creatorLevel",
            "baseName": "creator_level",
            "type": "Array<string>"
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202508SellerSearchCreatoronMarketplaceRequestBodyAdvancedFilters.attributeTypeMap;
    }
}

