/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202508UpdateTargetCollaborationResponseDataUpdateFailedAddProducts } from './UpdateTargetCollaborationResponseDataUpdateFailedAddProducts';
import { AffiliateSeller202508UpdateTargetCollaborationResponseDataUpdateFailedChangeCommissions } from './UpdateTargetCollaborationResponseDataUpdateFailedChangeCommissions';
import { AffiliateSeller202508UpdateTargetCollaborationResponseDataUpdateFailedSellerContactInfo } from './UpdateTargetCollaborationResponseDataUpdateFailedSellerContactInfo';

export class AffiliateSeller202508UpdateTargetCollaborationResponseDataUpdateFailed {
    /**
    * The list of creators\' TikTok User Open IDs that have not been successfully added. More details:https://partner.tiktokshop.com/docv2/page/3obfokj6
    */
    'addCreatorOpenIds'?: Array<string>;
    'addProducts'?: AffiliateSeller202508UpdateTargetCollaborationResponseDataUpdateFailedAddProducts;
    'changeCommissions'?: AffiliateSeller202508UpdateTargetCollaborationResponseDataUpdateFailedChangeCommissions;
    /**
    * The end time of the target collaboration, which has not been successfully updated.
    */
    'endTime'?: number;
    /**
    * The list of open id that caused the update to fail.
    */
    'invalidOpenIdList'?: Array<string>;
    /**
    * The list of product id that caused the update to fail.
    */
    'invalidProductIdList'?: Array<string>;
    /**
    * The name of the target collaboration.
    */
    'name'?: string;
    /**
    * The list of creators\' TikTok User Open IDs that have not been successfully removed. More details:https://partner.tiktokshop.com/docv2/page/3obfokj6
    */
    'removeCreatorOpenIds'?: Array<string>;
    /**
    * The list of product ids that have not been successfully removed.
    */
    'removeProductIds'?: Array<string>;
    'sellerContactInfo'?: AffiliateSeller202508UpdateTargetCollaborationResponseDataUpdateFailedSellerContactInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addCreatorOpenIds",
            "baseName": "add_creator_open_ids",
            "type": "Array<string>"
        },
        {
            "name": "addProducts",
            "baseName": "add_products",
            "type": "AffiliateSeller202508UpdateTargetCollaborationResponseDataUpdateFailedAddProducts"
        },
        {
            "name": "changeCommissions",
            "baseName": "change_commissions",
            "type": "AffiliateSeller202508UpdateTargetCollaborationResponseDataUpdateFailedChangeCommissions"
        },
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "number"
        },
        {
            "name": "invalidOpenIdList",
            "baseName": "invalid_open_id_list",
            "type": "Array<string>"
        },
        {
            "name": "invalidProductIdList",
            "baseName": "invalid_product_id_list",
            "type": "Array<string>"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "removeCreatorOpenIds",
            "baseName": "remove_creator_open_ids",
            "type": "Array<string>"
        },
        {
            "name": "removeProductIds",
            "baseName": "remove_product_ids",
            "type": "Array<string>"
        },
        {
            "name": "sellerContactInfo",
            "baseName": "seller_contact_info",
            "type": "AffiliateSeller202508UpdateTargetCollaborationResponseDataUpdateFailedSellerContactInfo"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202508UpdateTargetCollaborationResponseDataUpdateFailed.attributeTypeMap;
    }
}

