/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsCancelAndRefunds {
    /**
    * Canceled refers to units included in orders that were either \"Unpaid\" or \"Awaiting Shipment.\"
    */
    'canceled'?: number;
    /**
    * Refunded refers to units that were refunded but not returned.
    */
    'refunded'?: number;
    /**
    * Replacements refers to units that were returned and replaced. 
    */
    'replacements'?: number;
    /**
    * Returned refers to units that were returned and refunded. 
    */
    'returned'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "canceled",
            "baseName": "canceled",
            "type": "number"
        },
        {
            "name": "refunded",
            "baseName": "refunded",
            "type": "number"
        },
        {
            "name": "replacements",
            "baseName": "replacements",
            "type": "number"
        },
        {
            "name": "returned",
            "baseName": "returned",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202509GetShopProductPerformanceDetailResponseDataPerformanceIntervalsCancelAndRefunds.attributeTypeMap;
    }
}

