/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202509GetShopVideoPerformanceDetailsResponseDataPerformanceViewerProfileAgeDistribution {
    /**
    * Possible values: - 18-24 - 25-34 - 35-44 - 45-54 - 55+
    */
    'age'?: string;
    /**
    * Percentage of the corresponding age.
    */
    'percentage'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "age",
            "baseName": "age",
            "type": "string"
        },
        {
            "name": "percentage",
            "baseName": "percentage",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202509GetShopVideoPerformanceDetailsResponseDataPerformanceViewerProfileAgeDistribution.attributeTypeMap;
    }
}

