/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202509GetShopVideoPerformanceOverviewResponseDataPerformanceIntervalsGmv } from './GetShopVideoPerformanceOverviewResponseDataPerformanceIntervalsGmv';

export class Analytics202509GetShopVideoPerformanceOverviewResponseDataPerformanceIntervals {
    /**
    * Daily average number of customers.
    */
    'avgCustomers'?: number;
    /**
    * Ratio of the number of product clicks compared to number of video views in raw decimal format. To calculate the percentage, multiple it by 100%. Example: 0.0528 <=> 5.28%
    */
    'clickThroughRate'?: string;
    /**
    * End date of the interval (ISO 8601 YYYY-MM-DD format) in shop registered timezone, exclusive.
    */
    'endDate'?: string;
    'gmv'?: Analytics202509GetShopVideoPerformanceOverviewResponseDataPerformanceIntervalsGmv;
    /**
    * The number of product clicks from the video.
    */
    'productClicks'?: number;
    /**
    * The number of impressions of all video products.
    */
    'productImpressions'?: number;
    /**
    * The total number of paid SKU orders placed directly from all shoppable videos.
    */
    'skuOrders'?: number;
    /**
    * Start date of the interval (ISO 8601 YYYY-MM-DD format) in shop registered timezone, inclusive.
    */
    'startDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avgCustomers",
            "baseName": "avg_customers",
            "type": "number"
        },
        {
            "name": "clickThroughRate",
            "baseName": "click_through_rate",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "end_date",
            "type": "string"
        },
        {
            "name": "gmv",
            "baseName": "gmv",
            "type": "Analytics202509GetShopVideoPerformanceOverviewResponseDataPerformanceIntervalsGmv"
        },
        {
            "name": "productClicks",
            "baseName": "product_clicks",
            "type": "number"
        },
        {
            "name": "productImpressions",
            "baseName": "product_impressions",
            "type": "number"
        },
        {
            "name": "skuOrders",
            "baseName": "sku_orders",
            "type": "number"
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202509GetShopVideoPerformanceOverviewResponseDataPerformanceIntervals.attributeTypeMap;
    }
}

