/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Fbt202603CreateGoodsRequestBodyCreateGoodsDtoListBarcodeInfos } from './CreateGoodsRequestBodyCreateGoodsDtoListBarcodeInfos';
import { Fbt202603CreateGoodsRequestBodyCreateGoodsDtoListDimensionAndWeightBaseInfo } from './CreateGoodsRequestBodyCreateGoodsDtoListDimensionAndWeightBaseInfo';
import { Fbt202603CreateGoodsRequestBodyCreateGoodsDtoListHazmatInfo } from './CreateGoodsRequestBodyCreateGoodsDtoListHazmatInfo';
import { Fbt202603CreateGoodsRequestBodyCreateGoodsDtoListShelfLifeAttributeInfo } from './CreateGoodsRequestBodyCreateGoodsDtoListShelfLifeAttributeInfo';

export class Fbt202603CreateGoodsRequestBodyCreateGoodsDtoList {
    /**
    * barcode infos
    */
    'barcodeInfos'?: Array<Fbt202603CreateGoodsRequestBodyCreateGoodsDtoListBarcodeInfos>;
    /**
    * create goods type - CREATE_AND_BIND
    */
    'createGoodsType'?: string;
    'dimensionAndWeightBaseInfo'?: Fbt202603CreateGoodsRequestBodyCreateGoodsDtoListDimensionAndWeightBaseInfo;
    /**
    * goods image url
    */
    'goodsImageUrl'?: string;
    /**
    * goods name
    */
    'goodsName'?: string;
    'hazmatInfo'?: Fbt202603CreateGoodsRequestBodyCreateGoodsDtoListHazmatInfo;
    /**
    * whether is shelf life goods
    */
    'isExpirationManagement'?: boolean;
    /**
    * whether is hazmat goods
    */
    'isHazmat'?: boolean;
    /**
    * whether is expiration management goods
    */
    'isLotCode'?: boolean;
    /**
    * reference code
    */
    'referenceCode'?: string;
    /**
    * The return handling method applied when enabling the FBT customer return service, the default value will be Restock sellable, Dispose unsellable Possible values: -Dispose_of_all_returned_units -Restock_sellable_dispose_of_unsellable
    */
    'returnHandlingMethod'?: string;
    'shelfLifeAttributeInfo'?: Fbt202603CreateGoodsRequestBodyCreateGoodsDtoListShelfLifeAttributeInfo;
    /**
    * Identifier for Stock Keeping Unit (SKU) generated by TikTok Shop system
    */
    'ttsSkuId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "barcodeInfos",
            "baseName": "barcode_infos",
            "type": "Array<Fbt202603CreateGoodsRequestBodyCreateGoodsDtoListBarcodeInfos>"
        },
        {
            "name": "createGoodsType",
            "baseName": "create_goods_type",
            "type": "string"
        },
        {
            "name": "dimensionAndWeightBaseInfo",
            "baseName": "dimension_and_weight_base_info",
            "type": "Fbt202603CreateGoodsRequestBodyCreateGoodsDtoListDimensionAndWeightBaseInfo"
        },
        {
            "name": "goodsImageUrl",
            "baseName": "goods_image_url",
            "type": "string"
        },
        {
            "name": "goodsName",
            "baseName": "goods_name",
            "type": "string"
        },
        {
            "name": "hazmatInfo",
            "baseName": "hazmat_info",
            "type": "Fbt202603CreateGoodsRequestBodyCreateGoodsDtoListHazmatInfo"
        },
        {
            "name": "isExpirationManagement",
            "baseName": "is_expiration_management",
            "type": "boolean"
        },
        {
            "name": "isHazmat",
            "baseName": "is_hazmat",
            "type": "boolean"
        },
        {
            "name": "isLotCode",
            "baseName": "is_lot_code",
            "type": "boolean"
        },
        {
            "name": "referenceCode",
            "baseName": "reference_code",
            "type": "string"
        },
        {
            "name": "returnHandlingMethod",
            "baseName": "return_handling_method",
            "type": "string"
        },
        {
            "name": "shelfLifeAttributeInfo",
            "baseName": "shelf_life_attribute_info",
            "type": "Fbt202603CreateGoodsRequestBodyCreateGoodsDtoListShelfLifeAttributeInfo"
        },
        {
            "name": "ttsSkuId",
            "baseName": "tts_sku_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Fbt202603CreateGoodsRequestBodyCreateGoodsDtoList.attributeTypeMap;
    }
}

