/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Fbt202603UpdateGoodsRequestBodyUpdateGoodsDto } from './UpdateGoodsRequestBodyUpdateGoodsDto';

export class Fbt202603UpdateGoodsRequestBody {
    'updateGoodsDto'?: Fbt202603UpdateGoodsRequestBodyUpdateGoodsDto;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "updateGoodsDto",
            "baseName": "update_goods_dto",
            "type": "Fbt202603UpdateGoodsRequestBodyUpdateGoodsDto"
        }    ];

    static getAttributeTypeMap() {
        return Fbt202603UpdateGoodsRequestBody.attributeTypeMap;
    }
}

