/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Fbt202603UpdateGoodsRequestBodyUpdateGoodsDtoBarcodeInfos {
    /**
    * barcode type
    */
    'barcodeType'?: string;
    /**
    * barcode value
    */
    'barcodeValue'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "barcodeType",
            "baseName": "barcode_type",
            "type": "string"
        },
        {
            "name": "barcodeValue",
            "baseName": "barcode_value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Fbt202603UpdateGoodsRequestBodyUpdateGoodsDtoBarcodeInfos.attributeTypeMap;
    }
}

