/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202512GetShopLIVEProductsPerformanceListResponseDataProductsSalesAvgPrice } from './GetShopLIVEProductsPerformanceListResponseDataProductsSalesAvgPrice';
import { Analytics202512GetShopLIVEProductsPerformanceListResponseDataProductsSalesDirectGmv } from './GetShopLIVEProductsPerformanceListResponseDataProductsSalesDirectGmv';

export class Analytics202512GetShopLIVEProductsPerformanceListResponseDataProductsSales {
    'avgPrice'?: Analytics202512GetShopLIVEProductsPerformanceListResponseDataProductsSalesAvgPrice;
    /**
    * The total number of SKU orders created directly from the LIVE for this product.
    */
    'createdSkuOrders'?: number;
    /**
    * The total numbers of customers who ordered this product directly from the LIVE, including customers who made returns or refunds.
    */
    'customers'?: number;
    'directGmv'?: Analytics202512GetShopLIVEProductsPerformanceListResponseDataProductsSalesDirectGmv;
    /**
    * The number of product items sold
    */
    'itemsSold'?: number;
    /**
    * Total number of paid main orders placed. Main orders refer to the single purchase transaction a customer makes.
    */
    'mainOrders'?: number;
    /**
    * Main order paid / Main order created of this product
    */
    'paymentRate'?: string;
    /**
    * The total number of paid SKU orders placed directly from the LIVE for this product.
    */
    'skuOrders'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avgPrice",
            "baseName": "avg_price",
            "type": "Analytics202512GetShopLIVEProductsPerformanceListResponseDataProductsSalesAvgPrice"
        },
        {
            "name": "createdSkuOrders",
            "baseName": "created_sku_orders",
            "type": "number"
        },
        {
            "name": "customers",
            "baseName": "customers",
            "type": "number"
        },
        {
            "name": "directGmv",
            "baseName": "direct_gmv",
            "type": "Analytics202512GetShopLIVEProductsPerformanceListResponseDataProductsSalesDirectGmv"
        },
        {
            "name": "itemsSold",
            "baseName": "items_sold",
            "type": "number"
        },
        {
            "name": "mainOrders",
            "baseName": "main_orders",
            "type": "number"
        },
        {
            "name": "paymentRate",
            "baseName": "payment_rate",
            "type": "string"
        },
        {
            "name": "skuOrders",
            "baseName": "sku_orders",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202512GetShopLIVEProductsPerformanceListResponseDataProductsSales.attributeTypeMap;
    }
}

