/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Analytics202512GetShopLIVEProductsPerformanceListResponseDataProductsTrafficClickToOrderRate {
    /**
    * Percentage of times viewers who clicked LIVE product links also placed a main order.
    */
    'mainOrderCtor'?: string;
    /**
    * The percentage of times viewers clicked product links in LIVE streams and placed a direct order.
    */
    'skuOrderCtor'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mainOrderCtor",
            "baseName": "main_order_ctor",
            "type": "string"
        },
        {
            "name": "skuOrderCtor",
            "baseName": "sku_order_ctor",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202512GetShopLIVEProductsPerformanceListResponseDataProductsTrafficClickToOrderRate.attributeTypeMap;
    }
}

