/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202512GetShopLIVEProductsPerformanceListResponseDataProducts } from './GetShopLIVEProductsPerformanceListResponseDataProducts';

export class Analytics202512GetShopLIVEProductsPerformanceListResponseData {
    /**
    * Overall performance data for the video.
    */
    'products'?: Array<Analytics202512GetShopLIVEProductsPerformanceListResponseDataProducts>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<Analytics202512GetShopLIVEProductsPerformanceListResponseDataProducts>"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202512GetShopLIVEProductsPerformanceListResponseData.attributeTypeMap;
    }
}

