/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Order202507GetOrderDetailResponseDataOrdersLineItemsSubItemInfoItemTax } from './GetOrderDetailResponseDataOrdersLineItemsSubItemInfoItemTax';

export class Order202507GetOrderDetailResponseDataOrdersLineItemsSubItemInfo {
    /**
    * The cancellation reason. Please visit [our list of cancel reasons](https://partner.tiktokshop.com/docv2/page/67e61eee427345048595487d) for more information.
    */
    'cancelReason'?: string;
    /**
    * Cancellation request initiator. Available values: - `BUYER` - `SELLER` - `OPERATOR` - `SYSTEM`
    */
    'cancelUser'?: string;
    /**
    * Currency for payment.
    */
    'currency'?: string;
    /**
    * Available values: - `UNPAID`: The order has been placed, but payment has not yet completed. - `AWAITING_SHIPMENT`: The order is ready for shipment, but no items have been shipped yet. - `AWAITING_COLLECTION`: Shipping has been arranged, but the package is waiting to be collected by the carrier. - `IN_TRANSIT`: The package has been collected by the carrier and delivery is in progress. - `DELIVERED`: The package has been delivered to the buyer. - `COMPLETED`: The order has been completed, and no further returns or refunds are allowed. - `CANCELLED`: The order has been cancelled.
    */
    'displayStatus'?: string;
    /**
    * Line item id of the sub_item. This unique identifier can be used when performing split/line-level fulfillment events.
    */
    'id'?: string;
    /**
    * Whether the SKU is a hazmat item. When creating the label for a hazmat item, you must follow the platform rules to put certain items into one package. Please refer to the relationship between `sku_id` and `package_id` to determine how to follow platform rules.
    */
    'isDangerousGood'?: boolean;
    /**
    * Item tax detail.
    */
    'itemTax'?: Array<Order202507GetOrderDetailResponseDataOrdersLineItemsSubItemInfoItemTax>;
    /**
    * Item original price. Please refer to the currency of `payment_info`.
    */
    'originalPrice'?: string;
    /**
    * An order can contain one or more packages based on how the seller chooses to ship. Each package has a unique `package_id` and `tracking_id`.
    */
    'packageId'?: string;
    /**
    * The package status of the item. Available values: - `TO_FULFILL`: Package awaiting seller to arrange shipment. - `PROCESSING`: Shipping has been arranged by the seller. Awaiting carrier collection. - `FULFILLING`: Package has been collected by carrier and is in transit. - `COMPLETED`: Package has been delivered. - `CANCELLED`: Package has been canceled. Normally, the package is canceled due to the package being lost or damaged.
    */
    'packageStatus'?: string;
    /**
    * Platform discount amount. Please refer to the currency of `payment_info`.
    */
    'platformDiscount'?: string;
    /**
    * Product ID.
    */
    'productId'?: string;
    /**
    * Product name.
    */
    'productName'?: string;
    /**
    * Retail delivery fee (RDF). **Note**: Only available in the US market.
    */
    'retailDeliveryFee'?: string;
    /**
    * The time sellers shipped the order (called [Ship Package API](https://partner.tiktokshop.com/docv2/page/650aa4f1defece02be6e7cb1) successfully). Unix timestamp.
    */
    'rtsTime'?: number;
    /**
    * Item sale price. Please refer to the currency of `payment_info`.
    */
    'salePrice'?: string;
    /**
    * Seller discount amount. Please refer to the currency of `payment_info`.
    */
    'sellerDiscount'?: string;
    /**
    * The seller stock keeping unit (SKU) of the item.
    */
    'sellerSku'?: string;
    /**
    * The shipping provider ID of the item.
    */
    'shippingProviderId'?: string;
    /**
    * The shipping provider name.
    */
    'shippingProviderName'?: string;
    /**
    * SKU ID.
    */
    'skuId'?: string;
    /**
    * SKU image.
    */
    'skuImage'?: string;
    /**
    * The name of the SKU, combined by product SKU attribute like size or color. e.g. \"Black, 26\"
    */
    'skuName'?: string;
    /**
    * Tracking number. Available after package has been shipped.
    */
    'trackingNumber'?: string;
    /**
    * Seller warehouse ID.
    */
    'warehouseId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cancelReason",
            "baseName": "cancel_reason",
            "type": "string"
        },
        {
            "name": "cancelUser",
            "baseName": "cancel_user",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "displayStatus",
            "baseName": "display_status",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "isDangerousGood",
            "baseName": "is_dangerous_good",
            "type": "boolean"
        },
        {
            "name": "itemTax",
            "baseName": "item_tax",
            "type": "Array<Order202507GetOrderDetailResponseDataOrdersLineItemsSubItemInfoItemTax>"
        },
        {
            "name": "originalPrice",
            "baseName": "original_price",
            "type": "string"
        },
        {
            "name": "packageId",
            "baseName": "package_id",
            "type": "string"
        },
        {
            "name": "packageStatus",
            "baseName": "package_status",
            "type": "string"
        },
        {
            "name": "platformDiscount",
            "baseName": "platform_discount",
            "type": "string"
        },
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        },
        {
            "name": "productName",
            "baseName": "product_name",
            "type": "string"
        },
        {
            "name": "retailDeliveryFee",
            "baseName": "retail_delivery_fee",
            "type": "string"
        },
        {
            "name": "rtsTime",
            "baseName": "rts_time",
            "type": "number"
        },
        {
            "name": "salePrice",
            "baseName": "sale_price",
            "type": "string"
        },
        {
            "name": "sellerDiscount",
            "baseName": "seller_discount",
            "type": "string"
        },
        {
            "name": "sellerSku",
            "baseName": "seller_sku",
            "type": "string"
        },
        {
            "name": "shippingProviderId",
            "baseName": "shipping_provider_id",
            "type": "string"
        },
        {
            "name": "shippingProviderName",
            "baseName": "shipping_provider_name",
            "type": "string"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        },
        {
            "name": "skuImage",
            "baseName": "sku_image",
            "type": "string"
        },
        {
            "name": "skuName",
            "baseName": "sku_name",
            "type": "string"
        },
        {
            "name": "trackingNumber",
            "baseName": "tracking_number",
            "type": "string"
        },
        {
            "name": "warehouseId",
            "baseName": "warehouse_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Order202507GetOrderDetailResponseDataOrdersLineItemsSubItemInfo.attributeTypeMap;
    }
}

